// Каталоги маводҳои сохтмонӣ барои интихоби зуд дар Склад (Приход товара).
export type MaterialPreset = { group: string; name: string; unit: string };

export const MATERIAL_CATALOG: MaterialPreset[] = [
  { group: "Дюбель-гвоздь", name: "Дюбель-гвоздь 10×100 мм", unit: "dona" },
  { group: "Дюбель-гвоздь", name: "Дюбель-гвоздь 10×120 мм", unit: "dona" },
  { group: "Дюбель-гвоздь", name: "Дюбель-гвоздь 10×150 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 3.5×16 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 3.5×25 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 3.5×35 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 4×25 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 4×40 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 4×50 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 4.5×60 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 5×70 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 5×80 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 6×100 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 6×120 мм", unit: "dona" },
  { group: "Саморез", name: "Саморез 6×150 мм", unit: "dona" },
  { group: "Болт", name: "Болт 6×20 мм", unit: "dona" },
  { group: "Болт", name: "Болт 6×30 мм", unit: "dona" },
  { group: "Болт", name: "Болт 6×40 мм", unit: "dona" },
  { group: "Болт", name: "Болт 6×50 мм", unit: "dona" },
  { group: "Болт", name: "Болт 8×20 мм", unit: "dona" },
  { group: "Болт", name: "Болт 8×30 мм", unit: "dona" },
  { group: "Болт", name: "Болт 8×40 мм", unit: "dona" },
  { group: "Болт", name: "Болт 8×50 мм", unit: "dona" },
  { group: "Болт", name: "Болт 8×60 мм", unit: "dona" },
  { group: "Болт", name: "Болт 10×30 мм", unit: "dona" },
  { group: "Болт", name: "Болт 10×40 мм", unit: "dona" },
  { group: "Болт", name: "Болт 10×50 мм", unit: "dona" },
  { group: "Болт", name: "Болт 10×60 мм", unit: "dona" },
  { group: "Болт", name: "Болт 12×40 мм", unit: "dona" },
  { group: "Болт", name: "Болт 12×50 мм", unit: "dona" },
  { group: "Болт", name: "Болт 12×60 мм", unit: "dona" },
  { group: "Болт", name: "Болт 16×50 мм", unit: "dona" },
  { group: "Болт", name: "Болт 16×60 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 6 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 6 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 8 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 8 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 10 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 10 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 12 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 12 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 14 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 14 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 16 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 16 мм", unit: "dona" },
  { group: "Гайка", name: "Гайка 20 мм", unit: "dona" },
  { group: "Шайба", name: "Шайба 20 мм", unit: "dona" },
  { group: "Сими вязальный", name: "Сими вязальный 0.8 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 1.0 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 1.2 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 1.4 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 1.5 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 1.6 мм", unit: "kg" },
  { group: "Сими вязальный", name: "Сими вязальный 2.0 мм", unit: "kg" },
  { group: "Арматура", name: "Арматура 6 мм Ø6 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 8 мм Ø8 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 10 мм Ø10 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 12 мм Ø12 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 14 мм Ø14 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 16 мм Ø16 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 18 мм Ø18 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 20 мм Ø20 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 22 мм Ø22 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 25 мм Ø25 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 28 мм Ø28 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 32 мм Ø32 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 36 мм Ø36 мм", unit: "ton" },
  { group: "Арматура", name: "Арматура 40 мм Ø40 мм", unit: "ton" },
  { group: "Сетка арматурная", name: "Сетка 50×50 мм", unit: "m2" },
  { group: "Сетка арматурная", name: "Сетка 100×100 мм", unit: "m2" },
  { group: "Сетка арматурная", name: "Сетка 150×150 мм", unit: "m2" },
  { group: "Сетка арматурная", name: "Сетка 200×200 мм", unit: "m2" },
  { group: "Қум", name: "Қуми майда", unit: "m3" },
  { group: "Қум", name: "Қуми миёна", unit: "m3" },
  { group: "Қум", name: "Қуми калон", unit: "m3" },
  { group: "Қум", name: "Қуми шуста", unit: "m3" },
  { group: "Қум", name: "Қуми дарёӣ", unit: "m3" },
  { group: "Қум", name: "Қуми карьерӣ", unit: "m3" },
  { group: "Щебень", name: "Щебень 5–10 мм", unit: "m3" },
  { group: "Щебень", name: "Щебень 5–20 мм", unit: "m3" },
  { group: "Щебень", name: "Щебень 10–20 мм", unit: "m3" },
  { group: "Щебень", name: "Щебень 20–40 мм", unit: "m3" },
  { group: "Щебень", name: "Щебень 40–70 мм", unit: "m3" },
  { group: "Шағал", name: "Шағал 5–10 мм", unit: "m3" },
  { group: "Шағал", name: "Шағал 10–20 мм", unit: "m3" },
  { group: "Шағал", name: "Шағал 20–40 мм", unit: "m3" },
  { group: "Шағал", name: "Шағал 40–70 мм", unit: "m3" },
  { group: "Семент", name: "Семент М400 25 кг", unit: "bag" },
  { group: "Семент", name: "Семент М400 40 кг", unit: "bag" },
  { group: "Семент", name: "Семент М400 50 кг", unit: "bag" },
  { group: "Семент", name: "Семент М500 25 кг", unit: "bag" },
  { group: "Семент", name: "Семент М500 40 кг", unit: "bag" },
  { group: "Семент", name: "Семент М500 50 кг", unit: "bag" },
  { group: "Семент", name: "Семент М600 25 кг", unit: "bag" },
  { group: "Семент", name: "Семент М600 40 кг", unit: "bag" },
  { group: "Семент", name: "Семент М600 50 кг", unit: "bag" },
  { group: "Хишт", name: "Хишт сурх 250×120×65 мм", unit: "dona" },
  { group: "Хишт", name: "Хишт сурх 250×120×88 мм", unit: "dona" },
  { group: "Хишт", name: "Хишти рӯйпӯш 250×120×65 мм", unit: "dona" },
  { group: "Хишт", name: "Хишти силикатӣ 250×120×65 мм", unit: "dona" },
  { group: "Хишт", name: "Хишти шамотӣ 230×114×65 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×200×100 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×200×150 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×200×200 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×200×250 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×300×200 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×300×250 мм", unit: "dona" },
  { group: "Газоблок", name: "Газоблок 600×300×300 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×200×100 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×200×150 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×200×200 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×200×250 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×300×200 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×300×250 мм", unit: "dona" },
  { group: "Пеноблок", name: "Пеноблок 600×300×300 мм", unit: "dona" },
  { group: "Блок", name: "Шлакоблок 390×190×188 мм", unit: "dona" },
  { group: "Блок", name: "Блоки бетонӣ 390×190×188 мм", unit: "dona" },
  { group: "Блок", name: "Керамзитоблок 390×190×188 мм", unit: "dona" },
  { group: "Блок", name: "Перегородочный блок 390×90×188 мм", unit: "dona" },
  { group: "Тахта", name: "Тахта 20×100 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 25×100 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 25×150 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 30×100 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 30×150 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 40×100 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 40×150 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 50×100 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 50×150 мм", unit: "m3" },
  { group: "Тахта", name: "Тахта 50×200 мм", unit: "m3" },
  { group: "Брус", name: "Брус 50×50 мм", unit: "m3" },
  { group: "Брус", name: "Брус 50×100 мм", unit: "m3" },
  { group: "Брус", name: "Брус 50×150 мм", unit: "m3" },
  { group: "Брус", name: "Брус 50×200 мм", unit: "m3" },
  { group: "Брус", name: "Брус 100×100 мм", unit: "m3" },
  { group: "Брус", name: "Брус 100×150 мм", unit: "m3" },
  { group: "Брус", name: "Брус 100×200 мм", unit: "m3" },
  { group: "Брус", name: "Брус 150×150 мм", unit: "m3" },
  { group: "Брус", name: "Брус 150×200 мм", unit: "m3" },
  { group: "Брус", name: "Брус 200×200 мм", unit: "m3" },
  { group: "Рейка", name: "Рейка 20×20 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 20×30 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 20×40 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 25×25 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 25×40 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 30×40 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 40×50 мм", unit: "m" },
  { group: "Рейка", name: "Рейка 50×50 мм", unit: "m" },
  { group: "Фанера", name: "Фанера 4 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 6 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 9 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 12 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 15 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 18 мм", unit: "dona" },
  { group: "Фанера", name: "Фанера 21 мм", unit: "dona" },
  { group: "OSB", name: "OSB 6 мм", unit: "dona" },
  { group: "OSB", name: "OSB 9 мм", unit: "dona" },
  { group: "OSB", name: "OSB 12 мм", unit: "dona" },
  { group: "OSB", name: "OSB 15 мм", unit: "dona" },
  { group: "OSB", name: "OSB 18 мм", unit: "dona" },
  { group: "OSB", name: "OSB 22 мм", unit: "dona" },
  { group: "Пенопласт", name: "Пенопласт 20 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 30 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 40 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 50 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 60 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 80 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 100 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 120 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 150 мм", unit: "m2" },
  { group: "Пенопласт", name: "Пенопласт 200 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 20 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 30 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 40 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 50 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 80 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 100 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 120 мм", unit: "m2" },
  { group: "ЭППС", name: "ЭППС 150 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 30 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 50 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 80 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 100 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 120 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 150 мм", unit: "m2" },
  { group: "Минвата", name: "Минвата 200 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.35 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.40 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.45 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.50 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.60 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил 0.70 мм", unit: "m2" },
  { group: "Профнастил", name: "Профнастил C8", unit: "m2" },
  { group: "Профнастил", name: "Профнастил C10", unit: "m2" },
  { group: "Профнастил", name: "Профнастил C20", unit: "m2" },
  { group: "Профнастил", name: "Профнастил C21", unit: "m2" },
  { group: "Профнастил", name: "Профнастил HC35", unit: "m2" },
  { group: "Профнастил", name: "Профнастил H44", unit: "m2" },
  { group: "Профнастил", name: "Профнастил H57", unit: "m2" },
  { group: "Профнастил", name: "Профнастил H60", unit: "m2" },
  { group: "Профнастил", name: "Профнастил H75", unit: "m2" },
  { group: "Профнастил", name: "Профнастил H114", unit: "m2" },
  { group: "Металлочерепица", name: "Металлочерепица 0.40 мм", unit: "m2" },
  { group: "Металлочерепица", name: "Металлочерепица 0.45 мм", unit: "m2" },
  { group: "Металлочерепица", name: "Металлочерепица 0.50 мм", unit: "m2" },
  { group: "Металлочерепица", name: "Металлочерепица 0.60 мм", unit: "m2" },
  { group: "Шифер", name: "Шифер 6-волновой", unit: "dona" },
  { group: "Шифер", name: "Шифер 7-волновой", unit: "dona" },
  { group: "Шифер", name: "Шифер 8-волновой", unit: "dona" },
  { group: "Шифер", name: "Шифер 10-волновой", unit: "dona" },
  { group: "Рубероид", name: "Рубероид 10 м", unit: "rulon" },
  { group: "Рубероид", name: "Рубероид 15 м", unit: "rulon" },
  { group: "Рубероид", name: "Рубероид 20 м", unit: "rulon" },
  { group: "Рубероид", name: "Рубероид 25 м", unit: "rulon" },
  { group: "Гипсокартон", name: "ГКЛ 2500×1200×9.5 мм", unit: "dona" },
  { group: "Гипсокартон", name: "ГКЛ 2500×1200×12.5 мм", unit: "dona" },
  { group: "Гипсокартон", name: "ГКЛВ 2500×1200×9.5 мм", unit: "dona" },
  { group: "Гипсокартон", name: "ГКЛВ 2500×1200×12.5 мм", unit: "dona" },
  { group: "Гипсокартон", name: "ГКЛО 2500×1200×12.5 мм", unit: "dona" },
  { group: "Гипсокартон", name: "ГКЛО 2500×1200×15 мм", unit: "dona" },
  { group: "Профиль гипсокартон", name: "UD 27×28 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "CD 60×27 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "UW 50×40 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "UW 75×40 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "UW 100×40 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "CW 50×50 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "CW 75×50 мм", unit: "m" },
  { group: "Профиль гипсокартон", name: "CW 100×50 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 20 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 25 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 32 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 40 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 50 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 63 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 75 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 90 мм", unit: "m" },
  { group: "PPR труба", name: "PPR труба 110 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 32 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 40 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 50 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 75 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 110 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 160 мм", unit: "m" },
  { group: "Канализационная труба", name: "Канализация 200 мм", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 2×1.5 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 2×2.5 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 2×4 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 2×6 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 2×10 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×1.5 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×2.5 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×4 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×6 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×10 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 3×16 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 4×4 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 4×6 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 4×10 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 4×16 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×4 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×6 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×10 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×16 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×25 мм²", unit: "m" },
  { group: "Электрический кабель", name: "Кабель 5×35 мм²", unit: "m" },
  { group: "Гофра", name: "Гофра 16 мм", unit: "m" },
  { group: "Гофра", name: "Гофра 20 мм", unit: "m" },
  { group: "Гофра", name: "Гофра 25 мм", unit: "m" },
  { group: "Гофра", name: "Гофра 32 мм", unit: "m" },
  { group: "Гофра", name: "Гофра 40 мм", unit: "m" },
  { group: "Гофра", name: "Гофра 50 мм", unit: "m" },
  { group: "Автомат", name: "Автомат 6A", unit: "dona" },
  { group: "Автомат", name: "Автомат 10A", unit: "dona" },
  { group: "Автомат", name: "Автомат 16A", unit: "dona" },
  { group: "Автомат", name: "Автомат 20A", unit: "dona" },
  { group: "Автомат", name: "Автомат 25A", unit: "dona" },
  { group: "Автомат", name: "Автомат 32A", unit: "dona" },
  { group: "Автомат", name: "Автомат 40A", unit: "dona" },
  { group: "Автомат", name: "Автомат 50A", unit: "dona" },
  { group: "Автомат", name: "Автомат 63A", unit: "dona" },
  { group: "Шпаклёвка", name: "Шпаклёвка 5 кг", unit: "bag" },
  { group: "Шпаклёвка", name: "Шпаклёвка 10 кг", unit: "bag" },
  { group: "Шпаклёвка", name: "Шпаклёвка 20 кг", unit: "bag" },
  { group: "Шпаклёвка", name: "Шпаклёвка 25 кг", unit: "bag" },
  { group: "Клей плиточный", name: "Клей плиточный 5 кг", unit: "bag" },
  { group: "Клей плиточный", name: "Клей плиточный 10 кг", unit: "bag" },
  { group: "Клей плиточный", name: "Клей плиточный 20 кг", unit: "bag" },
  { group: "Клей плиточный", name: "Клей плиточный 25 кг", unit: "bag" },
  { group: "Клей для газоблока", name: "Клей для газоблока 20 кг", unit: "bag" },
  { group: "Клей для газоблока", name: "Клей для газоблока 25 кг", unit: "bag" },
  { group: "Монтажная пена", name: "Пена 300 мл", unit: "dona" },
  { group: "Монтажная пена", name: "Пена 500 мл", unit: "dona" },
  { group: "Монтажная пена", name: "Пена 650 мл", unit: "dona" },
  { group: "Монтажная пена", name: "Пена 750 мл", unit: "dona" },
  { group: "Монтажная пена", name: "Пена 850 мл", unit: "dona" },
  { group: "Грунтовка", name: "Грунтовка 1 л", unit: "dona" },
  { group: "Грунтовка", name: "Грунтовка 3 л", unit: "dona" },
  { group: "Грунтовка", name: "Грунтовка 5 л", unit: "dona" },
  { group: "Грунтовка", name: "Грунтовка 10 л", unit: "dona" },
  { group: "Грунтовка", name: "Грунтовка 20 л", unit: "dona" },
  { group: "Ранг", name: "Ранг 1 кг", unit: "bag" },
  { group: "Ранг", name: "Ранг 3 кг", unit: "bag" },
  { group: "Ранг", name: "Ранг 5 кг", unit: "bag" },
  { group: "Ранг", name: "Ранг 10 кг", unit: "bag" },
  { group: "Ранг", name: "Ранг 20 кг", unit: "bag" },
  { group: "Ранг", name: "Ранг 25 кг", unit: "bag" },
  { group: "Плитка настенная", name: "Плитка настенная 20×30 см", unit: "m2" },
  { group: "Плитка настенная", name: "Плитка настенная 25×40 см", unit: "m2" },
  { group: "Плитка настенная", name: "Плитка настенная 30×60 см", unit: "m2" },
  { group: "Плитка настенная", name: "Плитка настенная 40×80 см", unit: "m2" },
  { group: "Плитка настенная", name: "Плитка настенная 60×120 см", unit: "m2" },
  { group: "Плитка напольная", name: "Плитка напольная 30×30 см", unit: "m2" },
  { group: "Плитка напольная", name: "Плитка напольная 40×40 см", unit: "m2" },
  { group: "Плитка напольная", name: "Плитка напольная 45×45 см", unit: "m2" },
  { group: "Плитка напольная", name: "Плитка напольная 60×60 см", unit: "m2" },
  { group: "Плитка напольная", name: "Плитка напольная 60×120 см", unit: "m2" },
  { group: "Ламинат", name: "Ламинат 7 мм", unit: "m2" },
  { group: "Ламинат", name: "Ламинат 8 мм", unit: "m2" },
  { group: "Ламинат", name: "Ламинат 10 мм", unit: "m2" },
  { group: "Ламинат", name: "Ламинат 12 мм", unit: "m2" },
  { group: "Линолеум", name: "Линолеум 1.5 м", unit: "m" },
  { group: "Линолеум", name: "Линолеум 2.0 м", unit: "m" },
  { group: "Линолеум", name: "Линолеум 2.5 м", unit: "m" },
  { group: "Линолеум", name: "Линолеум 3.0 м", unit: "m" },
  { group: "Линолеум", name: "Линолеум 3.5 м", unit: "m" },
  { group: "Линолеум", name: "Линолеум 4.0 м", unit: "m" },
  { group: "Сантехника", name: "Муфта PPR 20 мм", unit: "dona" },
  { group: "Сантехника", name: "Муфта PPR 25 мм", unit: "dona" },
  { group: "Сантехника", name: "Муфта PPR 32 мм", unit: "dona" },
  { group: "Сантехника", name: "Уголок PPR 20 мм", unit: "dona" },
  { group: "Сантехника", name: "Уголок PPR 25 мм", unit: "dona" },
  { group: "Сантехника", name: "Тройник PPR 20 мм", unit: "dona" },
  { group: "Сантехника", name: "Тройник PPR 25 мм", unit: "dona" },
  { group: "Сантехника", name: "Тройник PPR 32 мм", unit: "dona" },
  { group: "Сантехника", name: "Кран PPR 20 мм", unit: "dona" },
  { group: "Сантехника", name: "Кран PPR 25 мм", unit: "dona" },
  { group: "Сантехника", name: "Кран PPR 32 мм", unit: "dona" },
  { group: "Сантехника", name: "Сифон 32 мм", unit: "dona" },
  { group: "Сантехника", name: "Сифон 40 мм", unit: "dona" },
  { group: "Сантехника", name: "Сифон 50 мм", unit: "dona" },
  { group: "Двери и окна", name: "Тирезаи ПВХ", unit: "dona" },
  { group: "Двери и окна", name: "Тирезаи алюминӣ", unit: "dona" },
  { group: "Двери и окна", name: "Дари металлӣ", unit: "dona" },
  { group: "Двери и окна", name: "Дари MDF", unit: "dona" },
  { group: "Двери и окна", name: "Дари чӯбӣ", unit: "dona" },
  { group: "Двери и окна", name: "Қулф", unit: "dona" },
  { group: "Двери и окна", name: "Дастак", unit: "dona" },
  { group: "Двери и окна", name: "Петля", unit: "dona" },
  { group: "Двери и окна", name: "Доводчик", unit: "dona" },
  { group: "Двери и окна", name: "Подоконник", unit: "dona" },
  { group: "Двери и окна", name: "Откос", unit: "dona" },
  { group: "Строительные материалы", name: "Монтажная лента", unit: "dona" },
  { group: "Строительные материалы", name: "Серпянка", unit: "dona" },
  { group: "Строительные материалы", name: "Герметик", unit: "dona" },
  { group: "Строительные материалы", name: "Силикон", unit: "dona" },
  { group: "Строительные материалы", name: "Гидроизоляционная мастика", unit: "dona" },
  { group: "Строительные материалы", name: "Пароизоляция", unit: "dona" },
  { group: "Строительные материалы", name: "Гидроизоляционная мембрана", unit: "dona" },
  { group: "Строительные материалы", name: "Фасадная сетка", unit: "dona" },
  { group: "Строительные материалы", name: "Клей фасадный", unit: "dona" },
  { group: "Строительные материалы", name: "Дюбель фасадный", unit: "dona" },
  { group: "Строительные материалы", name: "Уголок фасадный", unit: "dona" },
  { group: "Строительные материалы", name: "Затирка для плитки", unit: "dona" },
];

export const MATERIAL_GROUPS: string[] = Array.from(new Set(MATERIAL_CATALOG.map((m) => m.group)));

export function findMaterialPreset(name: string): MaterialPreset | undefined {
  const n = name.trim().toLowerCase();
  return MATERIAL_CATALOG.find((m) => m.name.toLowerCase() === n);
}
