const phrases: Record<string, string> = {
  "Файл аз 60 MB зиёд аст": "File az 60 MB ziyod ast",
  "Модели 3D бор карда шуд": "3D Boron Carda Shud Models",
  "Модели 3D-ро тоза кунам?": "3D-ro toza kunam models?",
  "Тоза шуд": "Toza Shud",
  "Иваз кардан": "Iwaz Cardan",
  "Бор кардан (.glb)": "Boron Cardan (.glb)",
  "Аз нав": "Az nov",
  "Шаб": "Shab",
  "Логотипи торик": "Logos TORIK",
  "Логотипи Kiosk": "Kiosk logos",
  "Логотип нав шуд": "Nav Shud logo",
  "Иваз шуда": "Iwaz Shuda",
  "Номи ширкат лозим": "Nomi shirkat lozim",
  "Сабт шуд": "Subt shud",
  "Логотип бор карда шуд": "Bor carda shud logo",
  "Нест кунам?": "Nest kunam?",
  "Иловаи ширкат": "Ilovai shirkat",
  "Аз галерея": "Az gallery",
  "Рад шуд": "Rad shud",
  "Лимит нав шуд": "Limit nav shud",
  "Илова шуд": "Ilova shud",
  "Миёна": "Miyona",
  "Матн ёфт нашуд": "Matt Euft Nashad",
  "Хатогии транскрипсия": "Khatogii transcription",
  "Тоза кардан": "Toza gimbal",
  "Муштарии нав: Али, +992 900...": "Nav mushtaria: Ali, +992 900...",
  "Хулосаи умумии ширкат": "Hulosai umummiyya shirkat",
  "Транскрипсия…": "Transcription…",
  "Сабт шуда истодааст…": "Sabt Shuda Istodaast...",
  "Паём нависед…": "We are hovering...",
  "Овоз сабт кун": "Ovoz subt kun",
  "Хурд": "Hurd",
  "Калон": "Kalon",
  "Чекро бор кунед": "Chekro Bor Kuned",
  "Нусха шуд": "Nuskha Shud",
  "Нусха кардан нашуд": "Nuskha cardan ushad",
  "Дархост фиристодан": "Darkhost pyristodane",
  "Шуъбаи Назорати Сохтмон": "Shubai Nazorati Sohtmon",
  "Табел": "Table",
  "Пудратчиён": "Poudratchiyon",
  "График Gantt": "Gantt chart",
  "Шуъбаи Кадр": "Shubai Frame",
  "Принимайте имущество клиента (авто, землю, дом и др.) в счёт оплаты недвижимости.": "Accept the client's property (cars, land, house, etc.) as payment for real estate.",
  "Удалить бартерную сделку? Связанная продажа и квартира будут освобождены.": "Delete the barter transaction? The associated sale and apartment will be exempt.",
  "не назначена": "unassigned",
  "таъин нашудааст": "ta 'in nashdaast",
  "Переплата (имущество дороже)": "Overpayment (property is more expensive)",
  "Даромад (факт)": "Daromad (actual)",
  "Фоидаи соф": "Foidai Sof",
  "Ширкат ёфт нашуд": "Shirkat Eft Nashad",
  "Сумма нодуруст": "Amount of nodurust",
  "Захира шуд": "Zahira Shud",
  "Сначала добавьте хотя бы одну страницу договора": "Please add at least one contract page first",
  "Договор распознан — проверьте поля": "Contract recognized — check the fields",
  "Не удалось распознать договор": "Failed to recognize contract",
  "Шартнома муайян карда нашуд": "Chartneau Muayan Carda Nashad",
  "Сурат": "Surat",
  "Сканирование...": "Scanning...",
  "Распознать и заполнить": "Recognize and fill in",
  "Шинохтан ва пур кардан": "Shinokhtan wa pur cardan",
  "Шарик илова шуд": "Silt noodle ball",
  "Нест шуд": "Nest shud",
  "Пардохт сабт шуд": "Pardocht sabt shud",
  "Ба шарикон": "Ba sharikon",
  "Ба хазинаи сохтмон": "Ba Khazinai Sokhtmon",
  "Фоизи шарикон": "Foizi Sharikon",
  "Интихоб кунед…": "Intihob kuned...",
  "Смета нест": "Estimate nest",
  "Номи смета лозим аст": "Nomi smeta lozim ast",
  "Смета сохта шуд": "Estimate Sokhta Sud",
  "Статус нав шуд": "Nav Shud Status",
  "Версияи нав сохта шуд": "Versiii Nav Sokhta Sud",
  "Аз смета зиёд": "Az smeta ziyod",
  "Ном лозим аст": "Nom lozim ast",
  "Нав шуд": "Nav Shud",
  "сатри нав": "satri nav",
  "Номро нависед ё интихоб кунед": "Nomro noved yo intihob kuned",
  "Масалан: Фундамент": "Masalan: Foundation",
  "Илова кардан": "Ilova Cardan",
  "Версия": "Version",
  "Фармоишгар": "Pharmoishgar",
  "Масъул": "Mas 'ul",
  "Ном": "Nom",
  "Браузер равзанаро баст": "Ravzanaro Bust Browser",
  "Ошёна (floor)": "Oshyona (floor)",
  "Ошёна": "Oshyona",
  "Ошёна нодуруст": "Oshyona nodurust",
  "Нарх нодуруст": "Narh Nodurust",
  "Нарх нодуруст аст": "Narh nodurust ast",
  "Хато": "Hato",
  "Файли Excel-ро интихоб кунед": "Excel-ro intihob quned files",
  "Импорт…": "Importing...",
  "Воридот…": "Voridot...",
  "Санаи таваллуд (YYYY-MM-DD)": "Sanai Tawallood (YYYY-MM-DD)",
  "Ахмедова Мадина": "Akhmedova Madina",
  "ФИО холист": "Full name of the holist",
  "Сана (YYYY-MM-DD)": "Sana 'a (YYYY-MM-DD)",
  "Корманд": "Kormand",
  "Хариди семент": "Haridi Cement",
  "Музди коргарон": "Muzdi corgaron",
  "Сана нодуруст": "Sana 'a Nodurust",
  "Сана нодуруст аст": "Sana 'a Nodurust Ast",
  "Ном (ширкат)": "Nom (shirkat)",
  "ООО Семент-Плюс": "Cement-Plus LLC",
  "Душанбе": "Dushanbe",
  "Каримов М.": "Karimov M.",
  "Таъминкунандагон": "Taminkunandagon",
  "Ном холист": "Nom Holist",
  "Семент М500": "Cement M500",
  "мешок": "bag",
  "халта": "halta",
  "Хишт": "Hisht",
  "шт": "pcs",
  "дона": "dona",
  "Ранг": "Rank",
  "Вазифа": "Wazifa",
  "Бригадир": "Foreman",
  "Каримов Мурод": "Karimov Murod",
  "Асозода Комрон": "Azozoda Comron",
  "Мардикор": "Mardicore",
  "Коргарон": "Corgaron",
  "Фурухта шуд": "Furukhta Sud",
  "Аввал шаблони шартномаро дар менюи «Договор» танзим кунед": "Avval templates chartnomaro gift menu and \"Contract\" tanzim kuned",
  "Пардохт шуд": "Pardocht shud",
  "Мунтазир": "Muntazir",
  "Схема": "Scheme",
  "Метраж": "Meter",
  "Нархи 1м²": "Narghi 1m²",
  "3D-тур": "3D tour",
  "Тамошо кунед": "Tamosho Kuned",
  "Паспортро сканер кунед": "Passport scanner kuned",
  "Шартнома": "Chartnoy",
  "Ба чоп омода": "Ba chop omoda",
  "ФИО ва телефон лозим": "Full name VA phone LOZIM",
  "ФИО*": "Full name*",
  "Телефон*": "Phone*",
  "Серияи паспорт": "Series and passport",
  "Санаи таваллуд": "Sanai Tawallood",
  "Санаи додашуда": "Sanai Addishuda",
  "Пардохти аввал": "Pardohti avwal",
  "Наздик": "Nazdik",
  "Дур": "Dur",
  "Сначала сделайте фото лицевой стороны паспорта": "Take a photo of the front of your passport first",
  "Данные распознаны": "Data recognized",
  "Не удалось распознать паспорт": "Failed to recognize passport",
  "Пеш": "Pesch",
  "Кафо": "Cafo",
  "Сканировать и заполнить": "Scan & Fill",
  "Нодуруст PIN": "Nodurust pin",
  "Барномаро кушоед": "Barnomaro Coucheshed",
  "PIN-кодро ворид кунед": "Vorid kuned pin",
  "Баромадан аз аккаунт": "Baromadan az account",
  "Удалить карточку переселения? Связанная продажа и квартира будут освобождены.": "Remove relocation card? Associated sale and apartment will be exempted.",
  "Компенсация переселенцу:": "Compensation to IDP:",
  "PIN сабт шуд": "Pin subt shud",
  "Линк нусха шуд": "Link nuskha shud",
  "PIN сабт шудааст • иваз кардан": "Pin sabt shudaast • ivaz cardan",
  "Иваз": "Iwaz",
  "Интихоби папкаи backup": "Intihobi folder backup",
  "PIN-кодро тоза кунем?": "Toza kunem pin code?",
  "PIN тоза шуд": "Pin toza shud",
  "PIN-код": "Pin",
  "PIN-и нав": "Pin and NAV",
  "Такрори PIN": "Takrori pin",
  "Гузоштани PIN": "Guzoshtany pin",
  "Тоза кардани PIN": "Cardan toza pin",
  "Расм хеле бузург аст": "Rasm hele buzurg ast",
  "Шаблони чек / квитанция": "Check / Receipt Templates",
  "Шаблони чек / квитансия": "Check /Receipt Templates",
  "Расми чек (замина)": "Rasmi check (zamina)",
  "Уплод кардан": "Cardan Liver",
  "ИНН/РМА": "Tin/RMA",
  "Ном ва насаби имзогузор": "Nom wa nasabi imzoguzor",
  "Директор: Ф.И.О.": "Director: full name",
  "Истифодабарандагони Binosoz.tj": "Istifodabarandagoni Binosoz.tj",
  "Сайт": "Website",
  "Ном ворид кунед": "Nom vorid kuned",
  "масалан: Фундамент": "masalan: Foundation",
  "все": "all",
  "ЖК": "LCD",
  "МФ": "MOF",
  "Все ЖК": "All LCD",
  "Все блоки": "All Blocks",
  "Только владелец может выдавать доступ": "Only the owner can grant access",
  "Не удалось создать пользователя": "Failed to create user",
  "Истифодабаранда сохта нашуд": "Istifodabaranda sochta nashud",
  "У вас нет компании": "You don't have a company",
  "Шумо ширкат надоред": "Noise shirkat nadored",
  "Проект не найден": "Project not found",
  "Блоки нав дар ЖК месозад.": "Blocks on the gift of LC mesozad.",
  "Муштарии нав.": "Mushtaria nav.",
  "Коргар илова мекунад.": "Corgar silt mekunad.",
  "Таъминкунанда илова мекунад.": "Taminkunanda silt mekunad.",
  "Техника илова мекунад.": "Mekunad silt technique.",
  "Блоки 1": "Units 1",
  "Этаж ёфт нашуд": "Euft naschud floor",
  "parent_project_id ё parent_project_name лозим": "parent_project_id his parent_project_name lozim",
  "Квартира ёфт нашуд": "Apartment yoft nashud",
  "customer_id ё customer_name/phone лозим": "customer_id ё customer_name/phone lozim",
  "Материал ёфт нашуд": "Material euft nashd",
  "LOVABLE_API_KEY нест": "LOVABLE_API_KEY NEST",
  "Агар ЖК блок надошта бошад ва этаж/квартира сохта шавад, аввал Блоки 1-ро худкор соз.": "Agar LCD block nadoshta boshad va floor/apartment sohta shavad, avwal Blocks 1-ro hudkor soz.",
  "Лимит-и AI зиёд шуд, каме сабр кунед": "Limit-i AI ziyod shud, kame sabr kuned",
  "Кредит-и AI Gateway тамом шуд": "Credit and AI Gateway tam shud",
  "Только владелец компании": "Only the owner of the company",
  "Только Super Admin": "Super Admin only",
  "Дархост ёфт нашуд": "Darkhost Euft Nashad",
  "Аллакай коркард шудааст": "Allakay korkard schudaast",
  "base64 лозим": "base64 lozim",
  "base64 лозим аст": "base64 lozim ast",
  "Лимит зиёд шуд, каме сабр кунед": "Limit ziyod shud, kame sabr kuned",
  "Кредити AI Gateway тамом шуд": "AI Gateway credits tham shud",
  "Кормандон": "Cormandon",
  "Заявка не найдена": "No ticket found",
  "Уже обработано": "Already Processed",
  "Дар дохили блок боз блок сохтан мумкин нест": "Dar dokhili block boz block sokhtan mumkin nest",
  "Корбар ёфт нашуд": "Corbar yoft nashud",
  "Email бояд бо аккаунти Google якхела бошад": "Email boyad because google accounts yakhela boshad",
  "Корбар сохта нашуд": "Corbar sochta naschud",
  "Тариф не найден": "Fare not found",
  "Тариф ёфт нашуд": "Tariff eoft ushd",
  "Директор": "Director",
  "Пудратчиён (Субподряд)": "Pudratchiyon (Subcontracting)",
  "График сохтмон (Gantt)": "Sochtmon schedule (Gantt)",
  "дона (шт)": "dona (pcs)",
  "метр (м)": "meter (m)",
  "метри мураббаъ (м²)": "murabba 'meter (m²)",
  "метри мукааб (м³)": "meters mukaab (m³)",
  "килограмм (кг)": "kilogram (kg)",
  "тонна (т)": "tonne (tonnes)",
  "грамм (г)": "gram (g)",
  "литр (л)": "liter (L)",
  "рулон": "roll",
  "баста": "basta",
  "комплект": "set",
  "бухта": "bay",
  "паллет": "pallet",
  "Фундамент": "Foundation",
  "Бом": "BOM",
  "Отделка": "Finish",
  "Арматура": "Reinforcement",
  "Экскаватор": "Excavator",
  "Кран": "Crane",
  "Самосвал": "Dump Truck",
  "Бетономешалка": "Concrete mixer",
  "Усто": "Usto",
  "Коргар": "Corgar",
  "Это фотографии бумажного шаблона договора купли-продажи квартиры (строительная компания).": "These are photos of the paper template of the contract of sale of the apartment (construction company).",
  "Извлеки реквизиты и текст договора строго в JSON по схеме.": "Extract the details and the text of the contract strictly in JSON according to the scheme.",
  "intro_text — вступительная часть (преамбула, кто/с кем).": "intro_text — introductory part (preamble, who/with whom).",
  "body_text — основные условия (пункты, права, оплата).": "body_text — basic conditions (clauses, rights, payment).",
  "footer_text — заключение и место для подписей.": "footer_text — conclusion and place for signatures.",
  "В тексте сохрани плейсхолдеры в фигурных скобках если они есть:": "In the text, save the placeholders in curly brackets, if any:",
  "Если в тексте упомянуты ФИО клиента, № квартиры, цена и т.п. — замени их на соответствующий плейсхолдер.": "If the text mentions the client's full name, apartment number, price, etc., replace them with the appropriate placeholder.",
  "Если поле не видно — поставь null.": "If the field is not visible, put null.",
  "Агар майдон намоён набошад – null гузоред.": "Maidon agar washed nabashad – null guzored.",
  "Ты — OCR-ассистент. Возвращай ТОЛЬКО валидный JSON-объект без пояснений и markdown.": "You are an OCR assistant. Return ONLY a valid JSON object without explanations and markdown.",
  "Лимит запросов исчерпан, попробуйте позже": "Request limit exhausted, please try again later",
  "Закончились AI-кредиты. Пополните в настройках Lovable.": "You're out of AI credits. Top up in your Lovable settings.",
  "Демо корбар": "Demo Corbar",
  "Демо аккаунт сохта нашуд": "Sokhta Nashad demo account",
  "Демо ширкат": "Demo Shirkat",
  "ЖК Ватан": "Vatan Residential Complex",
  "ЖК Сомон": "RC Somon",
  "Блоки А": "Blocks A",
  "Блоки Б": "Blocks B",
  "Семент 50 халта": "Cement 50 halta",
  "Маоши коргарон": "Maoshi Corgaron",
  "Каримов Карим": "Karimov Karim",
  "company_id талаб карда мешавад": "company_id talab carda meshavad",
  "Директор ёфт нашуд": "Director of Euft Nashud",
  "Илова:": "Ilova:",
  "Ошёна:": "Oshyona:",
  "File System Access API дар ин браузер дастрас нест": "File System Access API Dar in Browser Dastras Nest",
  "MARKETPLACE_SYNC_SECRET нест": "MARKETPLACE_SYNC_SECRET NEST",
  "Блок ёфт нашуд": "Euft naschud unit",
  "Marketplace URL барнагашт": "Marketplace URL barnagasht",
  "Это фото паспорта (Таджикистан / СНГ). Извлеки данные клиента строго в JSON по схеме.": "This is a photo of the passport (Tajikistan / CIS). Extract client data strictly in JSON according to the scheme.",
  "Если поле не видно — поставь null. Даты в формате YYYY-MM-DD.": "If the field is not visible, put null. Dates in YYYY-MM-DD format.",
  "ФИО полностью кириллицей, как в паспорте. Адрес прописки только из обратной стороны.": "Full name in Cyrillic alphabet, as in the passport. The address of the residence permit is only on the reverse side.",
  "Сомонӣ (TJS)": "Somoni (TJS)",
  "Рубль (RUB)": "Ruble (RUB)",
  "Доллар (USD)": "Dollar (USD)",
  "Квитанция": "Receipt",
  "СМС фаъол нест. Танзимоти OSON SMS-ро пур кунед.": "SMS faol unst. Tanzimoti OSON SMS-ro pur kuned.",
  "Маълумоти OSON SMS пурра нест (login / token / sender).": "Ma 'lumoti OSON SMS purra nest (login / token / sender).",
  "Только владелец может менять доступ": "Only the owner can change access",
  "Сотрудник не найден в вашей компании": "Employee not found in your company",
  "Корманд дар ширкати шумо ёфт нашуд": "Kormand Dar Shirkati Shumo Yoft Nashad",
  "ERP/CRM для строительных компаний: проекты, продажи квартир, платежи и расходы.": "ERP/CRM for construction companies: projects, apartment sales, payments and expenses.",
  "ERP/CRM для строительных компаний Таджикистана.": "ERP/CRM for construction companies in Tajikistan.",
  "ERP/CRM платформа для застройщиков: проекты, продажи, платежи, склад, смета.": "ERP/CRM platform for developers: projects, sales, payments, warehouse, estimates.",
  "Данные компании сохранены": "Company data saved",
  "Маълумоти ширкат захира шуд": "Ma 'lumoti shirkat zahira shud",
  "Название строительной компании": "Construction company name",
  "Ставьте вручную": "Set manually",
  "бессрочно": "indefinitely",
  "Проект / Блок": "Project / Unit",
  "Платёж": "Payment",
  "Пардохт": "Pardocht",
  "Складской товар": "Warehouse goods",
  "Моли анбор": "Moli anbor",
  "Приход на склад": "Warehouse Receipt",
  "Воридот ба анбор": "Voridot ba anbor",
  "Расход со склада": "Consumption from the warehouse",
  "Долг поставщику": "Debt to supplier",
  "Оплата поставщику": "Payment to supplier",
  "Пардохт ба молрасон": "Pardocht ba molrason",
  "Позиция сметы": "Estimate Item",
  "Рабочий": "Worker",
  "Документ клиента": "Customer document",
  "Восстановлено": "Restored",
  "Удалено навсегда": "Permanently deleted",
  "Корзина очищена": "Trash emptied",
  "Сабад тоза карда шуд": "Sabad toza carda shud",
  "Корзина пуста": "Cart is empty",
  "Удалённых записей нет.": "No records were deleted.",
  "Удалить навсегда? Это действие необратимо.": "Permanently delete? This action is irreversible.",
  "Демо удалено": "Demo deleted",
  "Демо нест карда шуд": "Demo nest card shud",
  "Все демо очищены": "All demos cleared",
  "Показывается всем посетителям.": "Shown to all visitors.",
  "Скрыта — новые демо-аккаунты создать нельзя.": "Hidden — no new demo accounts can be created.",
  "Отключить": "Disconnect",
  "Включить": "Enable",
  "Фаъол кардан": "Faol Cardan",
  "Демо-аккаунтов нет": "No demo accounts",
  "Активных демо-компаний не найдено.": "No active demo companies found.",
  "Ягон ширкати намоишии фаъол ёфт нашуд.": "Yagon shirkati namoishii faol yoft nashud.",
  "Все отзывы очищены": "All reviews cleared",
  "Очистить все отзывы? Это действие необратимо.": "Clear all reviews? This action is irreversible.",
  "Отзывов нет": "No reviews",
  "Пользователи demo пока ничего не прислали.": "Demo users haven't sent anything yet.",
  "Ваш ответ…": "Your answer…",
  "Изменить ответ": "Edit Reply",
  "Ответить": "Reply",
  "Открыть заново": "Reopen",
  "Аз нав кушодан": "Az Nav Kushodan",
  "Отметить как решено": "Mark as resolved",
  "Удалить отзыв?": "Delete review?",
  "Андешаро нест кунам?": "Andesharo nest kunam?",
  "Сохранение…": "Saving…",
  "Захира шудан…": "Zahira Shudan...",
  "Пакет интихоб кунед, ба картаи Super Admin пардохт кунед ва чекро бор кунед.": "Package of intihob kuned, ba kartai Super Admin pardocht kuned wa chekro bor kuned.",
  "Бастаро интихоб кунед, ба корти Super Admin пардохт кунед ва чекро бор кунед.": "Bastaro intihob kuned, ba korti Super Admin pardocht kuned wa chekro bor kuned.",
  "Табел коргарон — Binosoz.tj": "Table corgaron — Binosoz.tj",
  "Табели коргарон — Binosoz.tj": "Corgaron timesheets — Binosoz.tj",
  "Табел коргарон": "Table corgaron",
  "Табели коргарон": "Corgaron timesheets",
  "Коргарони фаъол": "Corgaroni faol",
  "Дар навбат": "Dar nawbat",
  "масалан: усто": "masalan: abutment",
  "PIN нав": "Pin NA",
  "Такрор": "Tacror",
  "Сабт кардан": "Subt cardan",
  "фаъол ✓": "faol ✓",
  "Выберите тариф и загрузите чек": "Choose a rate and upload your receipt",
  "Тарифро интихоб кунед ва чекро бор кунед": "Tarifro intihob kuned wa chekro bor kuned",
  "Подписка": "Subscription",
  "Обуна": "Aubunah",
  "Договор — Binosoz.tj": "Contract — Binosoz.tj",
  "Шартнома — Binosoz.tj": "Chartnoy — Binosoz.tj",
  "ДОГОВОР купли-продажи": "PURCHASE and sale agreement",
  "Лид (занг)": "Lead (zang)",
  "Тамос гирифт": "Tamos gyrift",
  "Гумшуда": "Gumshuda",
  "Лид илова шуд": "Lid silt shud",
  "Ном ва насаб": "Nom wa nasab",
  "Схемаи квартира": "Layouts and apartment",
  "Дашборд — Binosoz.tj": "Dashboard — Binosoz.tj",
  "Тамоми давра": "Tamomi Dawra",
  "Шуъба": "Shuba",
  "Харочот": "Harochot",
  "Склад / Коргарон": "Warehouse / Corgaron",
  "Должники — Binosoz.tj": "Debtors — Binosoz.tj",
  "Директор илова шуд": "Director of Silt Shud",
  "Парол иваз шуд": "Parol Iwaz Shud",
  "Техника — Binosoz.tj": "Machinery — Binosoz.tj",
  "Миксер": "Mixer",
  "Погрузчик": "Forklift",
  "Мошини боркаш": "Moshini Borkash",
  "Генератор": "Generator",
  "Ном лозим": "Nom Lozim",
  "Техника нест": "Technique nest",
  "Илова кунед": "Ilova Kuned",
  "Таъмир нест": "Ta 'mir nest",
  "Тавсиф лозим": "Tavsif Lozim",
  "ЖК → Блок": "LCD → Block",
  "Блокро интихоб кунед": "Blokro Intihob Kuned",
  "График сохтмон — Binosoz.tj": "Sochtmon schedule — Binosoz.tj",
  "Таъхиршуда": "Ta 'hirshuda",
  "Интихоб кунед": "Intihob kuned",
  "Kiosk кушода шуд": "Kiosk Kushoda Shud",
  "PIN-и нодуруст": "Pin and nodurust",
  "Kiosk фаъол нест": "Kiosk phaol nest",
  "PIN танзим нашуд": "Pin tanzim ushud",
  "Проектро интихоб кунед": "Projectro Intihob Kuned",
  "Блок → Ошёна → Квартира": "Block → Oshyona → Apartment",
  "Схема ва 3D тур": "Scheme va 3D tour",
  "Схемаи квартираро дидан ё тугмаи 3D-ро пахш карда сайри 360° кушода мешавад.": "Schemes and apartmentaro didan yo tugmai 3D-ro pahsh karda sairi 360° kushoda meshavad.",
  "Шартнома ва чоп": "Chartnoma wa chop",
  "Ба ман рост омад": "Ba man growth omad",
  "Гирифтам": "Giriftham",
  "Уведомления — Binosoz.tj": "Notifications — Binosoz.tj",
  "У проекта нет компании": "The project does not have a company",
  "СМС фиристода шуд": "SMS phyristode shud",
  "Гузаронидан": "Guzaronidan",
  "Имзогузор": "Imzoguzor",
  "Имзо": "Imzo",
  "Фиристодани СМС": "Phyristodani SMS",
  "СМС": "SMS",
  "Эслатма ба WhatsApp": "Eslatma ba WhatsApp",
  "Чоп чек": "Chop check",
  "Акт нест": "Act nest",
  "Комитет...": "The Committee...",
  "Кумита...": "Kumita...",
  "АКТ-001": "AKT-001",
  "Схема нест": "Nest scheme",
  "Ба Binosoz Market": "Ba Binosoz Market",
  "Кушодани кабинет дар Market": "Kushodani Cabinet Dar Market",
  "Блок илова шуд": "Sludge noodle block",
  "Укажите количество месяцев": "Specify the number of months",
  "например 8": "e.g. 8",
  "масалан 8": "masalan 8",
  "Поиск ФИО…": "Search full name...",
  "· пардохт шуд": "· Pardocht shud",
  "Добавьте приход материала, чтобы пополнить склад.": "Add the arrival of material to replenish the warehouse.",
  "Барои пур кардани анбор, воридоти маводро илова кунед.": "Baroi pur kardani anbor, voridoti mavoro silt kuned.",
  "Добавьте поступление материала.": "Add incoming material.",
  "Воридоти маводро илова кунед.": "Voridoti mavoro silt kuned.",
  "Спишите материал со склада проекта.": "Write off the material from the project warehouse.",
  "Укажите наименование": "Specify the name",
  "Выберите материал": "Select material",
  "Маводро интихоб кунед": "Maudoro Intihob Kuned",
  "Приход материала": "Material inflow",
  "Воридоти мавод": "Voridoti mavod",
  "Расход материала": "Material consumption",
  "Фото проекта": "Project photo",
  "Добавить фото": "Add photos",
  "Сурат илова кунед": "Surat silt kuned",
  "Радшуда": "Radshuda",
  "Баланд": "Baland",
  "Паст": "Paste",
  "нест": "nest",
  "GPS дастнорас": "GPS DATNORAS",
  "Озмоиши OSON SMS аз Binosoz.tj.": "Osmoishi OSON SMS az Binosoz.tj.",
  "Интеграцияи СМС (OSON SMS)": "Integration and SMS (OSON SMS)",
  "Интегратсияи SMS (OSON SMS)": "SMS Integrations (OSON SMS)",
  "Токен (Bearer token)": "Bearer token",
  "агар лозим бошад": "lozim boshad agar",
  "СМС-и худкорро фаъол мекунад": "SMS-i hudkorro faol mekunad",
  "Давра": "Davra",
  "Матни СМС": "Matni SMS",
  "Метках истифода баред:": "To the marks of istifod bared:",
  "ном": "nom",
  "сана": "sanah",
  "давра": "davra",
  "Матни паём": "Matni Paiom",
  "Выберите хотя бы один проект": "Please select at least one project",
  "Доступ к проектам": "Access to projects",
  "Сначала создайте проект.": "Create a project first.",
  "Прораб видит только выбранные проекты (и их блоки).": "The foreman sees only the selected projects (and their blocks).",
  "Бухгалтер видит все проекты компании.": "The accountant sees all the projects of the company.",
  "Доступ обновлён": "Access updated",
  "Доступ к страницам": "Accessing Pages",
  "Пудратчиён — Binosoz.tj": "Pudratchien — Binosoz.tj",
  "Бетонщик": "Concrete worker",
  "Электрик": "Electrician",
  "Сантехник": "Plumber",
  "Кафшергар": "Kafshergar",
  "Ремонт/Отделка": "Repair/Finish",
  "Таъмир/Ороиш": "Ta 'mir/Oroish",
  "Номи бригада лозим": "Nomi Lozim Brigade",
  "Бригада илова шуд": "Sludge Sludge Brigade",
  "Бригадаи нав илова кунед": "Nav Silt Kuned Brigades",
  "Мушкил фиристода шуд": "Mushkil pyristoda shud",
  "Мухтасар дар бораи мушкил": "Mukhtasar Dar Borai Mushkil",
  "муфассал баён кунед...": "mufassal Bayon Kuned...",
  "Муфассал баён кунед...": "Mufassal Bayon Kuned...",
  "Мушкилоти ман": "Mushkiloti man",
  "Табел-Kiosk — Binosoz.tj": "Table-Kiosk — Binosoz.tj",
  "Андоз аз даромад (13% — соддашуда)": "Andoz az daromad (13% — soddashuda)",
  "ААИ (VAT/НДС 14%)": "AAI (VAT/VAT 14%)",
  "Декларатсияи солона": "Declaratsiya Salt",
  "Показатель": "Indicator",
  "Значение": "Value",
  "Тип отчёта": "Report Type",
  "Период с": "Period from",
  "Давра аз": "Davra az",
  "Период по": "Period to",
  "Давра то": "Davra to",
  "Доход": "Income",
  "Даромад": "Daromad",
  "Прибыль": "Profit",
  "Фоида": "Foida",
  "Налог": "Tax",
  "Андоз": "Andoz",
  "Экспорт ба формати 1С": "Export ba 1C formats",
  "Декларатсия, андоз, экспорт ба 1С": "Declaratcia, andosis, export of ba 1C",
  "Супоридашуда": "Suporidashuda",
  "Супурдашуда": "Supurdashuda",
  "Супорида": "Suporida",
  "Супурда": "Supurda",
  "Давра лозим": "Davra Lozim",
  "Складских позиций пока нет": "No warehouse items yet",
  "Печать расхода": "Flow Seal",
  "Выберите ЖК": "Select LCD",
  "ЖК-ро интихоб кунед": "LCD Ro Intihob Kuned",
  "Выберите блок": "Select a block",
  "Блокро интихоб ку5нед": "Blokro intihob q5ned",
  "мепартояд": "mepartoiad",
  "Вход и регистрация — Binosoz.tj": "Login & Register — Binosoz.tj",
  "Вуруд ва сабти ном — Binosoz.tj": "Vouroud va sabti nom — Binosoz.tj",
  "Войдите в Binosoz.tj через Google или оставьте заявку на подключение вашей строительной компании.": "Log in to Binosoz.tj via Google or leave a request to connect your construction company.",
  "Вход в Binosoz.tj": "Login to Binosoz.tj",
  "Вуруд ба Binosoz.tj": "Vurud ba Binosoz.tj",
  "Доступ для владельцев строительных компаний и сотрудников: Google-вход и заявка на регистрацию.": "Access for construction company owners and employees: Google login and registration application.",
  "Бухгалтерский учёт в строительстве: полное руководство — Binosoz.tj": "Accounting in construction: a complete guide — Binosoz.tj",
  "Как вести бухгалтерский учёт в строительной компании: контроль расходов, документооборот, учёт проектов и материалов. Практическое руководство от Binosoz.tj.": "How to keep accounting records in a construction company: cost control, document management, accounting of projects and materials. A practical guide from Binosoz.tj.",
  "Бухгалтерский учёт в строительстве — руководство": "Accounting in Construction — Management",
  "Практическое руководство по бухгалтерскому учёту для застройщиков: расходы, склад, сметы и продажи в одной системе.": "A practical guide to accounting for developers: costs, warehouse, estimates and sales in one system.",
  "Бухгалтерский учёт в строительстве: полное руководство": "Accounting in Construction: A Complete Guide",
  "Как вести бухгалтерский учёт в строительной компании: контроль расходов, документооборот, учёт проектов и материалов.": "How to keep accounting records in a construction company: cost control, document management, accounting of projects and materials.",
  "Проекты, блоки, этажи, квартиры — единая иерархия учёта.": "Projects, blocks, floors, apartments — a single accounting hierarchy.",
  "Расходы и платежи с фильтром по ЖК и блоку, печатью и экспортом.": "Expenses and payments with filter by LCD and block, printing and export.",
  "Склад с приходом/расходом и автоматическим списанием на проект.": "Warehouse with receipt/consumption and automatic write-off to the project.",
  "Смета: планируемые статьи против фактических расходов.": "Estimate: planned items vs. actual costs.",
  "Продажи квартир, рассрочка, автоматические SMS о платежах.": "Sales of apartments, installments, automatic SMS about payments.",
  "Долги перед поставщиками и должники клиентов — в один клик.": "Debts to suppliers and debtors of customers — in one click.",
  "Роли и права: бухгалтер видит финансы, складчик — только склад.": "Roles and rights: the accountant sees the finances, the warehouseman only the warehouse.",
  "Binosoz.tj — ERP/CRM для строительных компаний": "Binosoz.tj — ERP/CRM for construction companies",
  "Платформа для застройщиков Таджикистана: проекты, продажи квартир, платежи, склад, смета и рассрочки в одном месте.": "Platform for Tajikistan developers: projects, apartment sales, payments, warehouse, estimates and installments in one place.",
  "Binosoz.tj — ERP/CRM для застройщиков": "Binosoz.tj — ERP/CRM for developers",
  "Ведите проекты, продажи квартир, рассрочки и финансы строительной компании в одной системе.": "Manage projects, apartment sales, installments and finances of the construction company in one system.",
  "Линк нодуруст аст": "Link nodurust ast",
  "Витринаи ЖК — BINO SOZ": "LCD showcases — Bino Soz",
  "Дархост фиристода шуд": "Dharkhost pyristoda shud",
  "Дархости шумо дар коркард": "Darkness noise gift corkard",
  "Дархост рад шуд": "Darkhost rad shud",
  "Дархости ширкат фиристед": "Darkness Shirkat Firisted",
  "Super Admin дархости шуморо дида мебарояд.": "Super Admin darkness shumoro dida mebaroid.",
  "Мутаассифона, дархост рад карда шуд. Метавонед аз нав фиристед.": "Mutaassifona, the darkhost is glad to carda shud. Metavoned az nav firisted.",
  "Экран кушода шуд": "Kushoda Shud Screen",
  "Кушодан": "Kushodan",
  "Безопасность и конфиденциальность — Binosoz.tj": "Security & Privacy — Binosoz.tj",
  "Амният ва махфият — Binosoz.tj": "Amniyat va makhfiyat — Binosoz.tj",
  "Как Binosoz.tj защищает данные строительных компаний: доступ по ролям, изоляция данных компаний и приватное хранение документов.": "How Binosoz.tj protects the data of construction companies: access by role, isolation of company data and private storage of documents.",
  "Обзор мер безопасности и конфиденциальности Binosoz.tj. Страница поддерживается владельцем приложения.": "Overview of security and privacy measures of Binosoz.tj. The page is maintained by the app owner.",
  "Безопасность и конфиденциальность": "Security & Privacy",
  "Амният ва махфият": "Amniyat wa makhfiyat",
  "Доступ и аутентификация": "Access and authentication",
  "Вход в систему защищён логином и паролем. Каждый сотрудник видит только те данные, к которым ему предоставлен доступ.": "Login is protected by login and password. Each employee sees only the data to which they have been granted access.",
  "Права разграничены по ролям (владелец, менеджер, бухгалтер, складчик), а роли хранятся отдельно и проверяются на стороне сервера.": "The rights are differentiated by roles (owner, manager, accountant, warehouseman), and the roles are stored separately and checked on the server side.",
  "Изоляция данных компаний": "Isolation of company data",
  "Данные каждой строительной компании отделены друг от друга. Сотрудники одной компании не видят проекты, клиентов, платежи или склад другой компании.": "The data of each construction company are separated from each other. Employees of one company do not see the projects, customers, payments or warehouse of another company.",
  "Доступ к проектам дополнительно ограничивается списком назначенных сотрудников.": "Access to projects is further limited by the list of assigned employees.",
  "Хранение данных": "Data retention",
};

export default phrases;