const phrases: Record<string, string> = {
  "Дашборд": "Dashboard",
  "Проектҳо": "Projects",
  "Клиентҳо": "Customers",
  "Пардохтҳо": "Payments",
  "Харочот": "Expenses",
  "Склад": "Warehouse",
  "Настройки": "Settings",
  "Поддержка": "Support",
  "Дастгирӣ": "Support",
  "Отдел продаж": "Sales department",
  "Юридический отдел": "Legal department",
  "Бухгалтерия": "Accounting",
  "Отдел контроля строительства": "Construction control",
  "Отдел кадров": "HR department",
  "Воронка продаж": "Sales pipeline",
  "Договор": "Contract",
  "Должники": "Debtors",
  "Разрешения": "Permits",
  "Государственные отчёты": "Government reports",
  "Снабженец": "Procurement",
  "Поставщики": "Suppliers",
  "Отчёт ОПУ": "P&L report",
  "Тарифы и оплата": "Plans and payment",
  "AI кредиты": "AI credits",
  "Скан кредиты": "Scan credits",
  "Табель": "Timesheet",
  "Подрядчики": "Contractors",
  "Техника": "Equipment",
  "Качество и безопасность": "Quality and safety",
  "Директора": "Directors",
  "Мои доли": "My shares",
  "Мой доход": "My income",
  "Кассир": "Cashier",
  "Повернуть экран": "Rotate screen",
  "Поворот экрана не поддерживается": "Screen rotation is not supported",
  "Не удалось повернуть экран. Браузер или устройство не поддерживает.": "Could not rotate the screen. The browser or device does not support it.",
  "Заблокировать приложение": "Lock the app",
  "Қулф кардани барнома": "Lock the app",
  "Вуруд ба система": "Login",
  "Дархости ширкат": "Company request",
  "Ворид шудан": "Log in",
  "Номи ширкат": "Company name",
  "Ному насаби соҳиб": "Owner full name",
  "Фиристодани дархост": "Send request",
  "Хуш омадед": "Welcome",
  "Эмайлро тасдиқ кунед ва ворид шавед.": "Confirm your email and log in.",
  "Навсозӣ…": "Updating…",
  "Нав шуд": "Updated",
  "Синхронизатсия": "Synchronization",
  "Ҳар 5 сония": "Every 5 seconds",
  "Хатогӣ ҳангоми боркунӣ": "Error while loading",
  "Продано квартир": "Apartments sold",
  "Свободных квартир": "Available apartments",
  "Клиенты с оплатой в системе": "Customers with payments in the system",
  "100% оплата": "100% payment",
  "Рассрочка": "Installment",
  "Пардохти ипотека (рассрочка)": "Mortgage payment (installment)",
  "Пардохтҳои тасдиқшуда": "Confirmed payments",
  "Коргарон": "Workers",
  "Бартер (мошинҳо)": "Barter (cars)",
  "Тақсими даромад": "Income distribution",
  "Бақияи умумӣ (шарикон + хазина)": "Total balance (partners + treasury)",
  "Ба шарикон": "To partners",
  "Ба хазинаи сохтмон": "To construction treasury",
  "Шарик": "Partner",
  "Шуъба": "Department",
  "Ҳама шуъбаҳо": "All departments",
  "Тамоми давра": "All time",
  "Даромад": "Income",
  "Зарари мошин": "Car damage",
  "Бақия": "Balance",
  "Пардохтшуда": "Paid",
  "Ҳисобшуда": "Calculated",
  "Пардохт": "Payment",
  "Маблағ": "Amount",
  "Эзоҳ": "Note",
  "Сабт кардан": "Save",
  "Қарздорӣ": "Debt",
  "Намуди ҷадвал": "Table view",
  "Нишондиҳанда": "Metric",
  "Қиймат": "Value",
  "Ҳисса": "Share",
  "Менеджер": "Manager",
  "Бухгалтер": "Accountant",
  "Складчик": "Warehouse keeper",
  "Директор": "Director",
  "Владелец": "Owner",
  "Карточкаҳо": "Cards",
  "Ҷадвали компактӣ": "Compact table",
  "Ҷадвали таҳлилӣ": "Analytics table",
  "Намуди васеъ": "Wide view",
  "Все время": "All time",
  "Сегодня": "Today",
  "Неделя": "Week",
  "Месяц": "Month",
  "Квартал": "Quarter",
  "Год": "Year",
  "Период": "Period",
  "Предыдущий месяц": "Previous month",
  "Следующий месяц": "Next month",
  "С": "From",
  "По": "To",
  "Расрочкаи": "Installments for",
  "Расрочкаи ин моҳ": "Installments this month",
  "карздор": "debtors",
  "қарздор": "debtors",
  "пардохт кард": "paid",
  "клиент": "clients",
  "муштарӣ": "customers",
  "аз": "from",
  "моҳ": "months",
  "Номаълум": "Unknown",
  "Маълумот нест": "No data",
  "Аз нав кӯшиш кардан": "Try again",
  "Пули расрочка аз рӯи моҳҳо": "Installment payments by month",
  "Муштариёни ипотека (рассрочка)": "Mortgage installment customers",
  "Январ": "January",
  "Феврал": "February",
  "Март": "March",
  "Апрел": "April",
  "Май": "May",
  "Июн": "June",
  "Июл": "July",
  "Август": "August",
  "Сентябр": "September",
  "Октябр": "October",
  "Ноябр": "November",
  "Декабр": "December",
};

export default phrases;