const phrases: Record<string, string> = {
  "Возможности": "Features",
  "Проблемы": "Problems",
  "Модули": "Modules",
  "Как это работает": "How it works",
  "Вопросы": "Questions",
  "Войти": "Log in",
  "Открыть систему": "Open system",
  "Начать бесплатно": "Start for free",
  "Оставить заявку": "Send request",
  "Управление стройкой": "Construction management",
  "Стройте объекты.": "Build projects.",
  "Управляйте цифрами.": "Control the numbers.",
  "Смотреть систему": "View the system",
  "Все процессы синхронизированы": "All processes are synchronized",
  "единая система": "one system",
  "Система изнутри": "Inside the system",
  "Вся стройка видна на одном экране": "The whole construction business on one screen",
  "Разделы системы": "System sections",
  "Цифровая экосистема": "Digital ecosystem",
  "Рабочий процесс": "Workflow",
  "Доступ по ролям": "Role-based access",
  "ERP для строительных компаний Таджикистана": "ERP for construction companies in Tajikistan",
  "Весь бизнес застройщика в одной системе": "The developer's whole business in one system",
  "Проекты, блоки и квартиры, продажи и рассрочка, платежи и долги, склад, смета, табель, зарплата и отчёты — всё работает вместе и обновляется в реальном времени.": "Projects, blocks and apartments, sales and installments, payments and debt, warehouse, estimates, timesheets, salaries and reports — all connected and updated in real time.",
  "Работает на телефоне и компьютере": "Works on phone and computer",
  "Русский, таджикский и English": "Russian, Tajik and English",
  "Русский, таджикский и English — язык переключается одной кнопкой.": "Russian, Tajik and English — switch the language with one button.",
  "Данные каждой компании изолированы": "Each company's data is isolated",
  "модулей в системе": "modules in the system",
  "языка интерфейса": "interface languages",
  "доступ из любой точки": "access from anywhere",
  "ручных таблиц Excel": "manual Excel tables",
  "Всё, что нужно застройщику": "Everything a developer needs",
  "Каждый модуль можно включить по мере роста компании — начните с проектов и продаж.": "Each module can be enabled as the company grows — start with projects and sales.",
  "Проекты и блоки": "Projects and blocks",
  "Проект → блок → этаж → квартира. Наглядная шахматка со статусами квартир.": "Project → block → floor → apartment. A clear apartment grid with statuses.",
  "Проект → блок → этаж → квартира": "Project → block → floor → apartment",
  "Продажи и рассрочка": "Sales and installments",
  "Договор, первый взнос, график рассрочки на любое число месяцев и контроль оплат.": "Contract, first payment, installment schedule for any number of months, and payment control.",
  "CRM-воронка": "CRM pipeline",
  "Заявки клиентов, этапы сделки и напоминания менеджерам.": "Customer requests, deal stages, and reminders for managers.",
  "Клиенты": "Customers",
  "Единая база покупателей с документами и историей платежей.": "A single customer database with documents and payment history.",
  "Платежи и должники": "Payments and debtors",
  "Приход денег, просрочки и автоматические напоминания в WhatsApp и СМС.": "Money received, overdue payments, and automatic WhatsApp and SMS reminders.",
  "Касса": "Cash register",
  "Смены кассира, приход и расход наличных, Z-отчёт по смене.": "Cashier shifts, cash income and expenses, and shift Z-reports.",
  "Расходы и поставщики": "Expenses and suppliers",
  "Расходы по проектам, счета поставщиков и контроль задолженности.": "Project expenses, supplier invoices, and debt control.",
  "Смета": "Estimate",
  "Версии сметы, автоматический расчёт и сравнение плана с фактом.": "Estimate versions, automatic calculation, and plan-vs-actual comparison.",
  "Склад": "Warehouse",
  "Приход, расход и остатки материалов; списание прямо на проект.": "Material receipts, usage and stock balances; write-offs directly to a project.",
  "Снабжение": "Procurement",
  "Заявки на материалы от прорабов и контроль закупок.": "Material requests from foremen and purchasing control.",
  "Табель и посещаемость": "Timesheet and attendance",
  "Отметка рабочих на объекте через киоск-экран и расчёт смен.": "Worker check-in on site through a kiosk screen and shift calculation.",
  "Сотрудники и роли": "Employees and roles",
  "Владелец, бухгалтер, складчик, прораб — у каждого свой доступ.": "Owner, accountant, warehouse manager, foreman — each has their own access.",
  "Субподрядчики": "Subcontractors",
  "Объёмы работ, акты и расчёты с бригадами.": "Work volumes, acceptance acts, and crew settlements.",
  "Техника": "Equipment",
  "Учёт техники, работы и простоев на объектах.": "Equipment, work, and downtime tracking on sites.",
  "Договоры и разрешения": "Contracts and permits",
  "Шаблоны договоров, сроки разрешительных документов и напоминания.": "Contract templates, permit deadlines, and reminders.",
  "Качество и график": "Quality and schedule",
  "Замечания по качеству и план-график работ (Гант).": "Quality notes and work schedule (Gantt).",
  "Отчёты и налоги": "Reports and taxes",
  "Выручка, расходы, прибыль по проектам и налоговые отчёты.": "Revenue, expenses, project profit, and tax reports.",
  "WhatsApp и СМС": "WhatsApp and SMS",
  "Автоматические уведомления клиентам о платежах и напоминания.": "Automatic payment notifications and reminders for customers.",
  "Сканер паспорта (AI)": "Passport scanner (AI)",
  "Данные клиента распознаются с фото паспорта за секунды.": "Customer data is read from a passport photo in seconds.",
  "Дашборд директора": "Director dashboard",
  "Ключевые цифры компании на одном экране в реальном времени.": "Key company numbers on one screen in real time.",
  "Шахматка квартир": "Apartment grid",
  "Доли и пайщики": "Shares and partners",
  "Учёт долей партнёров и распределение прибыли.": "Partner share accounting and profit distribution.",
  "Переселение и бартер": "Resettlement and barter",
  "Сделки по переселению жильцов и бартерные договорённости.": "Resident resettlement deals and barter agreements.",
  "Запуск за один день": "Launch in one day",
  "Регистрируете компанию": "Register the company",
  "Создаёте аккаунт владельца и получаете свою изолированную базу.": "Create the owner's account and get your isolated company database.",
  "Добавляете проект и квартиры": "Add a project and apartments",
  "Блоки, этажи, квартиры и цены — шахматка строится автоматически.": "Blocks, floors, apartments and prices — the grid is built automatically.",
  "Подключаете сотрудников": "Connect employees",
  "Каждому сотруднику — своя роль и доступ только к своим данным.": "Each employee gets a role and access only to their own data.",
  "Работаете и смотрите цифры": "Work and watch the numbers",
  "Продажи, платежи и расходы сразу видны в отчётах и на дашборде.": "Sales, payments and expenses are immediately visible in reports and on the dashboard.",
  "Данные вашей компании под защитой": "Your company data is protected",
  "Доступ по ролям, изоляция данных между компаниями, приватное хранение документов и проверка прав на стороне сервера при каждом запросе.": "Role-based access, isolated company data, private document storage, and server-side permission checks on every request.",
  "Подробнее о безопасности": "More about security",
  "Частые вопросы": "Frequently asked questions",
  "Сколько стоит?": "How much does it cost?",
  "Начать можно бесплатно. Тариф зависит от количества проектов и сотрудников — напишите нам, подберём подходящий.": "You can start for free. Pricing depends on the number of projects and employees — contact us and we will choose the right plan.",
  "Нужно ли устанавливать программу?": "Do I need to install software?",
  "Нет. Система работает в браузере на телефоне, планшете и компьютере.": "No. The system works in a browser on phone, tablet, and computer.",
  "Можно перенести данные из Excel?": "Can data be imported from Excel?",
  "Да, мы помогаем перенести список квартир, клиентов и графики рассрочки.": "Yes, we help import apartment lists, customers, and installment schedules.",
  "На каком языке интерфейс?": "Which languages does the interface support?",
  "Данные каждой компании изолированы, доступ по ролям, документы хранятся приватно.": "Each company's data is isolated, access is role-based, and documents are stored privately.",
  "Готовы навести порядок в компании?": "Ready to bring order to your company?",
  "Создайте аккаунт и добавьте первый проект уже сегодня.": "Create an account and add your first project today.",
  "Все права защищены.": "All rights reserved.",
  "Безопасность": "Security",
  "От продажи квартир": "From apartment sales",
  "до управления стройкой": "to construction management",
  "Единая система для строительной компании: проекты, продажи, рассрочка, платежи, склад, смета, табель и отчёты.": "A single system for a construction company: projects, sales, installments, payments, warehouse, estimates, timesheets, and reports.",
  "Проблема": "Problem",
  "Знакомая ситуация?": "Does this sound familiar?",
  "Если хотя бы один пункт про вашу компанию — Binosoz.tj заменит таблицы, чаты и стопки бумаг.": "If even one point matches your company, Binosoz.tj replaces spreadsheets, chats, and piles of paper.",
  "Застройщик": "Developer",
  "Продажи живут в Excel и чатах": "Sales live in Excel and chats",
  "Excel вместо CRM": "Excel instead of CRM",
  "У каждого менеджера свой файл. Клиенты и история сделок теряются.": "Each manager has a separate file. Customers and deal history get lost.",
  "WhatsApp вместо системы": "WhatsApp instead of a system",
  "Квартиру забронировали в чате. Кто, когда и на каких условиях — никто не помнит.": "An apartment was booked in a chat. Who, when, and on what terms — nobody remembers.",
  "Бумажные договоры": "Paper contracts",
  "Каждый договор — час правок: опечатки, реквизиты и версии документа.": "Every contract takes an hour of edits: typos, details, and document versions.",
  "Нет аналитики": "No analytics",
  "Сколько заработали и где теряем деньги — становится ясно слишком поздно.": "How much was earned and where money is lost becomes clear too late.",
  "Стройка и склад": "Construction and warehouse",
  "Расходы считают в тетради": "Expenses are counted in notebooks",
  "Материалы без учёта": "Materials without tracking",
  "Цемент привезли, часть пропала — остатки никто не сверяет.": "Cement arrives, some disappears — nobody checks balances.",
  "Рабочие без табеля": "Workers without timesheets",
  "Кто вышел на объект и сколько смен — считают по памяти.": "Who came to the site and how many shifts they worked is counted from memory.",
  "Смета отдельно от факта": "Estimate separate from actuals",
  "План в одном файле, реальные расходы — в другом.": "The plan is in one file, real expenses are in another.",
  "Долги клиентов": "Customer debts",
  "Кто просрочил рассрочку, узнаёте только в конце месяца.": "You only learn who is late on installments at the end of the month.",
  "Одна система — вся компания": "One system — the whole company",
  "Binosoz.tj закрывает весь цикл: от первой заявки клиента до последнего отчёта по прибыли.": "Binosoz.tj covers the full cycle: from the first customer request to the final profit report.",
  "Продажи": "Sales",
  "CRM, шахматка, договоры": "CRM, apartment grid, contracts",
  "Полный цикл": "Full cycle",
  "2 в 1": "2 in 1",
  "Стройка": "Construction",
  "Склад, смета, табель": "Warehouse, estimates, timesheets",
  "Платформа": "Platform",
  "Этаж": "Floor",
  "Свободно": "Available",
  "Продано": "Sold",
  "Рассрочка": "Installment",
  "Недоступно": "Unavailable",
};

export default phrases;
