/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PassportOcrRouteImport } from './routes/passport-ocr'
import { Route as PassportPreviewRouteImport } from './routes/passport-preview'
import { Route as PassportReviewRouteImport } from './routes/passport-review'
import { Route as PassportScanRouteImport } from './routes/passport-scan'
import { Route as PassportScannerRouteImport } from './routes/passport-scanner'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAiCreditsRouteImport } from './routes/_app/ai-credits'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppCashierRouteImport } from './routes/_app/cashier'
import { Route as AppContractsRouteImport } from './routes/_app/contracts'
import { Route as AppCrmFunnelRouteImport } from './routes/_app/crm-funnel'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDebtorsRouteImport } from './routes/_app/debtors'
import { Route as AppDirectorsRouteImport } from './routes/_app/directors'
import { Route as AppEquipmentRouteImport } from './routes/_app/equipment'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppGanttRouteImport } from './routes/_app/gantt'
import { Route as AppKioskRouteImport } from './routes/_app/kiosk'
import { Route as AppMyEarningsRouteImport } from './routes/_app/my-earnings'
import { Route as AppMySharesRouteImport } from './routes/_app/my-shares'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPayablesRouteImport } from './routes/_app/payables'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppPermitsRouteImport } from './routes/_app/permits'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppScanCreditsRouteImport } from './routes/_app/scan-credits'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSubcontractorsRouteImport } from './routes/_app/subcontractors'
import { Route as AppSupplyRouteImport } from './routes/_app/supply'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppTabelKioskRouteImport } from './routes/_app/tabel-kiosk'
import { Route as AppTaxReportsRouteImport } from './routes/_app/tax-reports'
import { Route as AppWarehouseRouteImport } from './routes/_app/warehouse'
import { Route as AppWhatsappRouteImport } from './routes/_app/whatsapp'
import { Route as BlogAccountingGuideRouteImport } from './routes/blog.accounting-guide'
import { Route as KioskScreenTokenRouteImport } from './routes/kiosk-screen.$token'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as TabelScreenTokenRouteImport } from './routes/tabel-screen.$token'
import { Route as AppKioskIndexRouteImport } from './routes/_app/kiosk/index'
import { Route as AppKioskProjectIdRouteImport } from './routes/_app/kiosk/$projectId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects/$id'
import { Route as ApiPublicExportDatabaseRouteImport } from './routes/api/public/export/database'
import { Route as ApiPublicExportStorageRouteImport } from './routes/api/public/export/storage'
import { Route as ApiPublicHooksApartmentSyncRouteImport } from './routes/api/public/hooks/apartment-sync'
import { Route as ApiPublicHooksFunnelInboundRouteImport } from './routes/api/public/hooks/funnel-inbound'
import { Route as ApiPublicHooksPartnerSyncRouteImport } from './routes/api/public/hooks/partner-sync'
import { Route as ApiPublicHooksSmsRemindersRouteImport } from './routes/api/public/hooks/sms-reminders'
import { Route as ApiPublicHooksWhatsappLeadsRouteImport } from './routes/api/public/hooks/whatsapp-leads'
import { Route as ApiPublicWaVoiceFileRouteImport } from './routes/api/public/wa-voice.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportOcrRoute = PassportOcrRouteImport.update({
  id: '/passport-ocr',
  path: '/passport-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportPreviewRoute = PassportPreviewRouteImport.update({
  id: '/passport-preview',
  path: '/passport-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportReviewRoute = PassportReviewRouteImport.update({
  id: '/passport-review',
  path: '/passport-review',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportScanRoute = PassportScanRouteImport.update({
  id: '/passport-scan',
  path: '/passport-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportScannerRoute = PassportScannerRouteImport.update({
  id: '/passport-scanner',
  path: '/passport-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCreditsRoute = AppAiCreditsRouteImport.update({
  id: '/ai-credits',
  path: '/ai-credits',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierRoute = AppCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmFunnelRoute = AppCrmFunnelRouteImport.update({
  id: '/crm-funnel',
  path: '/crm-funnel',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorsRoute = AppDirectorsRouteImport.update({
  id: '/directors',
  path: '/directors',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppGanttRoute = AppGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => AppRoute,
} as any)
const AppKioskRoute = AppKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AppRoute,
} as any)
const AppMyEarningsRoute = AppMyEarningsRouteImport.update({
  id: '/my-earnings',
  path: '/my-earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppMySharesRoute = AppMySharesRouteImport.update({
  id: '/my-shares',
  path: '/my-shares',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesRoute = AppPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsRoute = AppPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppScanCreditsRoute = AppScanCreditsRouteImport.update({
  id: '/scan-credits',
  path: '/scan-credits',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSubcontractorsRoute = AppSubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplyRoute = AppSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTabelKioskRoute = AppTabelKioskRouteImport.update({
  id: '/tabel-kiosk',
  path: '/tabel-kiosk',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxReportsRoute = AppTaxReportsRouteImport.update({
  id: '/tax-reports',
  path: '/tax-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const BlogAccountingGuideRoute = BlogAccountingGuideRouteImport.update({
  id: '/blog/accounting-guide',
  path: '/blog/accounting-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskScreenTokenRoute = KioskScreenTokenRouteImport.update({
  id: '/kiosk-screen/$token',
  path: '/kiosk-screen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelScreenTokenRoute = TabelScreenTokenRouteImport.update({
  id: '/tabel-screen/$token',
  path: '/tabel-screen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKioskIndexRoute = AppKioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKioskRoute,
} as any)
const AppKioskProjectIdRoute = AppKioskProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppKioskRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicExportDatabaseRoute = ApiPublicExportDatabaseRouteImport.update({
  id: '/api/public/export/database',
  path: '/api/public/export/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportStorageRoute = ApiPublicExportStorageRouteImport.update({
  id: '/api/public/export/storage',
  path: '/api/public/export/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksApartmentSyncRoute =
  ApiPublicHooksApartmentSyncRouteImport.update({
    id: '/api/public/hooks/apartment-sync',
    path: '/api/public/hooks/apartment-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFunnelInboundRoute =
  ApiPublicHooksFunnelInboundRouteImport.update({
    id: '/api/public/hooks/funnel-inbound',
    path: '/api/public/hooks/funnel-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPartnerSyncRoute =
  ApiPublicHooksPartnerSyncRouteImport.update({
    id: '/api/public/hooks/partner-sync',
    path: '/api/public/hooks/partner-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSmsRemindersRoute =
  ApiPublicHooksSmsRemindersRouteImport.update({
    id: '/api/public/hooks/sms-reminders',
    path: '/api/public/hooks/sms-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappLeadsRoute =
  ApiPublicHooksWhatsappLeadsRouteImport.update({
    id: '/api/public/hooks/whatsapp-leads',
    path: '/api/public/hooks/whatsapp-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaVoiceFileRoute = ApiPublicWaVoiceFileRouteImport.update({
  id: '/api/public/wa-voice/$file',
  path: '/api/public/wa-voice/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/passport-ocr': typeof PassportOcrRoute
  '/passport-preview': typeof PassportPreviewRoute
  '/passport-review': typeof PassportReviewRoute
  '/passport-scan': typeof PassportScanRoute
  '/passport-scanner': typeof PassportScannerRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AppAdminRoute
  '/ai-credits': typeof AppAiCreditsRoute
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/cashier': typeof AppCashierRoute
  '/contracts': typeof AppContractsRoute
  '/crm-funnel': typeof AppCrmFunnelRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/debtors': typeof AppDebtorsRoute
  '/directors': typeof AppDirectorsRoute
  '/equipment': typeof AppEquipmentRoute
  '/expenses': typeof AppExpensesRoute
  '/gantt': typeof AppGanttRoute
  '/kiosk': typeof AppKioskRouteWithChildren
  '/my-earnings': typeof AppMyEarningsRoute
  '/my-shares': typeof AppMySharesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payables': typeof AppPayablesRoute
  '/payments': typeof AppPaymentsRoute
  '/permits': typeof AppPermitsRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/scan-credits': typeof AppScanCreditsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/subcontractors': typeof AppSubcontractorsRoute
  '/supply': typeof AppSupplyRoute
  '/support': typeof AppSupportRoute
  '/tabel-kiosk': typeof AppTabelKioskRoute
  '/tax-reports': typeof AppTaxReportsRoute
  '/warehouse': typeof AppWarehouseRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/blog/accounting-guide': typeof BlogAccountingGuideRoute
  '/kiosk-screen/$token': typeof KioskScreenTokenRoute
  '/p/$id': typeof PIdRoute
  '/tabel-screen/$token': typeof TabelScreenTokenRoute
  '/kiosk/$projectId': typeof AppKioskProjectIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/kiosk/': typeof AppKioskIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/api/public/export/database': typeof ApiPublicExportDatabaseRoute
  '/api/public/export/storage': typeof ApiPublicExportStorageRoute
  '/api/public/hooks/apartment-sync': typeof ApiPublicHooksApartmentSyncRoute
  '/api/public/hooks/funnel-inbound': typeof ApiPublicHooksFunnelInboundRoute
  '/api/public/hooks/partner-sync': typeof ApiPublicHooksPartnerSyncRoute
  '/api/public/hooks/sms-reminders': typeof ApiPublicHooksSmsRemindersRoute
  '/api/public/hooks/whatsapp-leads': typeof ApiPublicHooksWhatsappLeadsRoute
  '/api/public/wa-voice/$file': typeof ApiPublicWaVoiceFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/passport-ocr': typeof PassportOcrRoute
  '/passport-preview': typeof PassportPreviewRoute
  '/passport-review': typeof PassportReviewRoute
  '/passport-scan': typeof PassportScanRoute
  '/passport-scanner': typeof PassportScannerRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AppAdminRoute
  '/ai-credits': typeof AppAiCreditsRoute
  '/attendance': typeof AppAttendanceRoute
  '/billing': typeof AppBillingRoute
  '/cashier': typeof AppCashierRoute
  '/contracts': typeof AppContractsRoute
  '/crm-funnel': typeof AppCrmFunnelRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/debtors': typeof AppDebtorsRoute
  '/directors': typeof AppDirectorsRoute
  '/equipment': typeof AppEquipmentRoute
  '/expenses': typeof AppExpensesRoute
  '/gantt': typeof AppGanttRoute
  '/my-earnings': typeof AppMyEarningsRoute
  '/my-shares': typeof AppMySharesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payables': typeof AppPayablesRoute
  '/payments': typeof AppPaymentsRoute
  '/permits': typeof AppPermitsRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/scan-credits': typeof AppScanCreditsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/subcontractors': typeof AppSubcontractorsRoute
  '/supply': typeof AppSupplyRoute
  '/support': typeof AppSupportRoute
  '/tabel-kiosk': typeof AppTabelKioskRoute
  '/tax-reports': typeof AppTaxReportsRoute
  '/warehouse': typeof AppWarehouseRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/blog/accounting-guide': typeof BlogAccountingGuideRoute
  '/kiosk-screen/$token': typeof KioskScreenTokenRoute
  '/p/$id': typeof PIdRoute
  '/tabel-screen/$token': typeof TabelScreenTokenRoute
  '/kiosk/$projectId': typeof AppKioskProjectIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/kiosk': typeof AppKioskIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/api/public/export/database': typeof ApiPublicExportDatabaseRoute
  '/api/public/export/storage': typeof ApiPublicExportStorageRoute
  '/api/public/hooks/apartment-sync': typeof ApiPublicHooksApartmentSyncRoute
  '/api/public/hooks/funnel-inbound': typeof ApiPublicHooksFunnelInboundRoute
  '/api/public/hooks/partner-sync': typeof ApiPublicHooksPartnerSyncRoute
  '/api/public/hooks/sms-reminders': typeof ApiPublicHooksSmsRemindersRoute
  '/api/public/hooks/whatsapp-leads': typeof ApiPublicHooksWhatsappLeadsRoute
  '/api/public/wa-voice/$file': typeof ApiPublicWaVoiceFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/passport-ocr': typeof PassportOcrRoute
  '/passport-preview': typeof PassportPreviewRoute
  '/passport-review': typeof PassportReviewRoute
  '/passport-scan': typeof PassportScanRoute
  '/passport-scanner': typeof PassportScannerRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-credits': typeof AppAiCreditsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/cashier': typeof AppCashierRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/crm-funnel': typeof AppCrmFunnelRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debtors': typeof AppDebtorsRoute
  '/_app/directors': typeof AppDirectorsRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/gantt': typeof AppGanttRoute
  '/_app/kiosk': typeof AppKioskRouteWithChildren
  '/_app/my-earnings': typeof AppMyEarningsRoute
  '/_app/my-shares': typeof AppMySharesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payables': typeof AppPayablesRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/permits': typeof AppPermitsRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scan-credits': typeof AppScanCreditsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/subcontractors': typeof AppSubcontractorsRoute
  '/_app/supply': typeof AppSupplyRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/tabel-kiosk': typeof AppTabelKioskRoute
  '/_app/tax-reports': typeof AppTaxReportsRoute
  '/_app/warehouse': typeof AppWarehouseRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/blog/accounting-guide': typeof BlogAccountingGuideRoute
  '/kiosk-screen/$token': typeof KioskScreenTokenRoute
  '/p/$id': typeof PIdRoute
  '/tabel-screen/$token': typeof TabelScreenTokenRoute
  '/_app/kiosk/$projectId': typeof AppKioskProjectIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/kiosk/': typeof AppKioskIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/api/public/export/database': typeof ApiPublicExportDatabaseRoute
  '/api/public/export/storage': typeof ApiPublicExportStorageRoute
  '/api/public/hooks/apartment-sync': typeof ApiPublicHooksApartmentSyncRoute
  '/api/public/hooks/funnel-inbound': typeof ApiPublicHooksFunnelInboundRoute
  '/api/public/hooks/partner-sync': typeof ApiPublicHooksPartnerSyncRoute
  '/api/public/hooks/sms-reminders': typeof ApiPublicHooksSmsRemindersRoute
  '/api/public/hooks/whatsapp-leads': typeof ApiPublicHooksWhatsappLeadsRoute
  '/api/public/wa-voice/$file': typeof ApiPublicWaVoiceFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/passport-ocr'
    | '/passport-preview'
    | '/passport-review'
    | '/passport-scan'
    | '/passport-scanner'
    | '/pending'
    | '/sitemap.xml'
    | '/trust'
    | '/admin'
    | '/ai-credits'
    | '/attendance'
    | '/billing'
    | '/cashier'
    | '/contracts'
    | '/crm-funnel'
    | '/customers'
    | '/dashboard'
    | '/debtors'
    | '/directors'
    | '/equipment'
    | '/expenses'
    | '/gantt'
    | '/kiosk'
    | '/my-earnings'
    | '/my-shares'
    | '/notifications'
    | '/payables'
    | '/payments'
    | '/permits'
    | '/quality'
    | '/reports'
    | '/scan-credits'
    | '/settings'
    | '/staff'
    | '/subcontractors'
    | '/supply'
    | '/support'
    | '/tabel-kiosk'
    | '/tax-reports'
    | '/warehouse'
    | '/whatsapp'
    | '/blog/accounting-guide'
    | '/kiosk-screen/$token'
    | '/p/$id'
    | '/tabel-screen/$token'
    | '/kiosk/$projectId'
    | '/projects/$id'
    | '/kiosk/'
    | '/projects/'
    | '/api/public/export/database'
    | '/api/public/export/storage'
    | '/api/public/hooks/apartment-sync'
    | '/api/public/hooks/funnel-inbound'
    | '/api/public/hooks/partner-sync'
    | '/api/public/hooks/sms-reminders'
    | '/api/public/hooks/whatsapp-leads'
    | '/api/public/wa-voice/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/passport-ocr'
    | '/passport-preview'
    | '/passport-review'
    | '/passport-scan'
    | '/passport-scanner'
    | '/pending'
    | '/sitemap.xml'
    | '/trust'
    | '/admin'
    | '/ai-credits'
    | '/attendance'
    | '/billing'
    | '/cashier'
    | '/contracts'
    | '/crm-funnel'
    | '/customers'
    | '/dashboard'
    | '/debtors'
    | '/directors'
    | '/equipment'
    | '/expenses'
    | '/gantt'
    | '/my-earnings'
    | '/my-shares'
    | '/notifications'
    | '/payables'
    | '/payments'
    | '/permits'
    | '/quality'
    | '/reports'
    | '/scan-credits'
    | '/settings'
    | '/staff'
    | '/subcontractors'
    | '/supply'
    | '/support'
    | '/tabel-kiosk'
    | '/tax-reports'
    | '/warehouse'
    | '/whatsapp'
    | '/blog/accounting-guide'
    | '/kiosk-screen/$token'
    | '/p/$id'
    | '/tabel-screen/$token'
    | '/kiosk/$projectId'
    | '/projects/$id'
    | '/kiosk'
    | '/projects'
    | '/api/public/export/database'
    | '/api/public/export/storage'
    | '/api/public/hooks/apartment-sync'
    | '/api/public/hooks/funnel-inbound'
    | '/api/public/hooks/partner-sync'
    | '/api/public/hooks/sms-reminders'
    | '/api/public/hooks/whatsapp-leads'
    | '/api/public/wa-voice/$file'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/passport-ocr'
    | '/passport-preview'
    | '/passport-review'
    | '/passport-scan'
    | '/passport-scanner'
    | '/pending'
    | '/sitemap.xml'
    | '/trust'
    | '/_app/admin'
    | '/_app/ai-credits'
    | '/_app/attendance'
    | '/_app/billing'
    | '/_app/cashier'
    | '/_app/contracts'
    | '/_app/crm-funnel'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/debtors'
    | '/_app/directors'
    | '/_app/equipment'
    | '/_app/expenses'
    | '/_app/gantt'
    | '/_app/kiosk'
    | '/_app/my-earnings'
    | '/_app/my-shares'
    | '/_app/notifications'
    | '/_app/payables'
    | '/_app/payments'
    | '/_app/permits'
    | '/_app/quality'
    | '/_app/reports'
    | '/_app/scan-credits'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/subcontractors'
    | '/_app/supply'
    | '/_app/support'
    | '/_app/tabel-kiosk'
    | '/_app/tax-reports'
    | '/_app/warehouse'
    | '/_app/whatsapp'
    | '/blog/accounting-guide'
    | '/kiosk-screen/$token'
    | '/p/$id'
    | '/tabel-screen/$token'
    | '/_app/kiosk/$projectId'
    | '/_app/projects/$id'
    | '/_app/kiosk/'
    | '/_app/projects/'
    | '/api/public/export/database'
    | '/api/public/export/storage'
    | '/api/public/hooks/apartment-sync'
    | '/api/public/hooks/funnel-inbound'
    | '/api/public/hooks/partner-sync'
    | '/api/public/hooks/sms-reminders'
    | '/api/public/hooks/whatsapp-leads'
    | '/api/public/wa-voice/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PassportOcrRoute: typeof PassportOcrRoute
  PassportPreviewRoute: typeof PassportPreviewRoute
  PassportReviewRoute: typeof PassportReviewRoute
  PassportScanRoute: typeof PassportScanRoute
  PassportScannerRoute: typeof PassportScannerRoute
  PendingRoute: typeof PendingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  BlogAccountingGuideRoute: typeof BlogAccountingGuideRoute
  KioskScreenTokenRoute: typeof KioskScreenTokenRoute
  PIdRoute: typeof PIdRoute
  TabelScreenTokenRoute: typeof TabelScreenTokenRoute
  ApiPublicExportDatabaseRoute: typeof ApiPublicExportDatabaseRoute
  ApiPublicExportStorageRoute: typeof ApiPublicExportStorageRoute
  ApiPublicHooksApartmentSyncRoute: typeof ApiPublicHooksApartmentSyncRoute
  ApiPublicHooksFunnelInboundRoute: typeof ApiPublicHooksFunnelInboundRoute
  ApiPublicHooksPartnerSyncRoute: typeof ApiPublicHooksPartnerSyncRoute
  ApiPublicHooksSmsRemindersRoute: typeof ApiPublicHooksSmsRemindersRoute
  ApiPublicHooksWhatsappLeadsRoute: typeof ApiPublicHooksWhatsappLeadsRoute
  ApiPublicWaVoiceFileRoute: typeof ApiPublicWaVoiceFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-ocr': {
      id: '/passport-ocr'
      path: '/passport-ocr'
      fullPath: '/passport-ocr'
      preLoaderRoute: typeof PassportOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-preview': {
      id: '/passport-preview'
      path: '/passport-preview'
      fullPath: '/passport-preview'
      preLoaderRoute: typeof PassportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-review': {
      id: '/passport-review'
      path: '/passport-review'
      fullPath: '/passport-review'
      preLoaderRoute: typeof PassportReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-scan': {
      id: '/passport-scan'
      path: '/passport-scan'
      fullPath: '/passport-scan'
      preLoaderRoute: typeof PassportScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-scanner': {
      id: '/passport-scanner'
      path: '/passport-scanner'
      fullPath: '/passport-scanner'
      preLoaderRoute: typeof PassportScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-credits': {
      id: '/_app/ai-credits'
      path: '/ai-credits'
      fullPath: '/ai-credits'
      preLoaderRoute: typeof AppAiCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier': {
      id: '/_app/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AppCashierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm-funnel': {
      id: '/_app/crm-funnel'
      path: '/crm-funnel'
      fullPath: '/crm-funnel'
      preLoaderRoute: typeof AppCrmFunnelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debtors': {
      id: '/_app/debtors'
      path: '/debtors'
      fullPath: '/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directors': {
      id: '/_app/directors'
      path: '/directors'
      fullPath: '/directors'
      preLoaderRoute: typeof AppDirectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gantt': {
      id: '/_app/gantt'
      path: '/gantt'
      fullPath: '/gantt'
      preLoaderRoute: typeof AppGanttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kiosk': {
      id: '/_app/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AppKioskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-earnings': {
      id: '/_app/my-earnings'
      path: '/my-earnings'
      fullPath: '/my-earnings'
      preLoaderRoute: typeof AppMyEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-shares': {
      id: '/_app/my-shares'
      path: '/my-shares'
      fullPath: '/my-shares'
      preLoaderRoute: typeof AppMySharesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payables': {
      id: '/_app/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof AppPayablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permits': {
      id: '/_app/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof AppPermitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan-credits': {
      id: '/_app/scan-credits'
      path: '/scan-credits'
      fullPath: '/scan-credits'
      preLoaderRoute: typeof AppScanCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subcontractors': {
      id: '/_app/subcontractors'
      path: '/subcontractors'
      fullPath: '/subcontractors'
      preLoaderRoute: typeof AppSubcontractorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supply': {
      id: '/_app/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof AppSupplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tabel-kiosk': {
      id: '/_app/tabel-kiosk'
      path: '/tabel-kiosk'
      fullPath: '/tabel-kiosk'
      preLoaderRoute: typeof AppTabelKioskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax-reports': {
      id: '/_app/tax-reports'
      path: '/tax-reports'
      fullPath: '/tax-reports'
      preLoaderRoute: typeof AppTaxReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouse': {
      id: '/_app/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/accounting-guide': {
      id: '/blog/accounting-guide'
      path: '/blog/accounting-guide'
      fullPath: '/blog/accounting-guide'
      preLoaderRoute: typeof BlogAccountingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk-screen/$token': {
      id: '/kiosk-screen/$token'
      path: '/kiosk-screen/$token'
      fullPath: '/kiosk-screen/$token'
      preLoaderRoute: typeof KioskScreenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabel-screen/$token': {
      id: '/tabel-screen/$token'
      path: '/tabel-screen/$token'
      fullPath: '/tabel-screen/$token'
      preLoaderRoute: typeof TabelScreenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/kiosk/': {
      id: '/_app/kiosk/'
      path: '/'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof AppKioskIndexRouteImport
      parentRoute: typeof AppKioskRoute
    }
    '/_app/kiosk/$projectId': {
      id: '/_app/kiosk/$projectId'
      path: '/$projectId'
      fullPath: '/kiosk/$projectId'
      preLoaderRoute: typeof AppKioskProjectIdRouteImport
      parentRoute: typeof AppKioskRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/export/database': {
      id: '/api/public/export/database'
      path: '/api/public/export/database'
      fullPath: '/api/public/export/database'
      preLoaderRoute: typeof ApiPublicExportDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/export/storage': {
      id: '/api/public/export/storage'
      path: '/api/public/export/storage'
      fullPath: '/api/public/export/storage'
      preLoaderRoute: typeof ApiPublicExportStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apartment-sync': {
      id: '/api/public/hooks/apartment-sync'
      path: '/api/public/hooks/apartment-sync'
      fullPath: '/api/public/hooks/apartment-sync'
      preLoaderRoute: typeof ApiPublicHooksApartmentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/funnel-inbound': {
      id: '/api/public/hooks/funnel-inbound'
      path: '/api/public/hooks/funnel-inbound'
      fullPath: '/api/public/hooks/funnel-inbound'
      preLoaderRoute: typeof ApiPublicHooksFunnelInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/partner-sync': {
      id: '/api/public/hooks/partner-sync'
      path: '/api/public/hooks/partner-sync'
      fullPath: '/api/public/hooks/partner-sync'
      preLoaderRoute: typeof ApiPublicHooksPartnerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sms-reminders': {
      id: '/api/public/hooks/sms-reminders'
      path: '/api/public/hooks/sms-reminders'
      fullPath: '/api/public/hooks/sms-reminders'
      preLoaderRoute: typeof ApiPublicHooksSmsRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-leads': {
      id: '/api/public/hooks/whatsapp-leads'
      path: '/api/public/hooks/whatsapp-leads'
      fullPath: '/api/public/hooks/whatsapp-leads'
      preLoaderRoute: typeof ApiPublicHooksWhatsappLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa-voice/$file': {
      id: '/api/public/wa-voice/$file'
      path: '/api/public/wa-voice/$file'
      fullPath: '/api/public/wa-voice/$file'
      preLoaderRoute: typeof ApiPublicWaVoiceFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppKioskRouteChildren {
  AppKioskProjectIdRoute: typeof AppKioskProjectIdRoute
  AppKioskIndexRoute: typeof AppKioskIndexRoute
}

const AppKioskRouteChildren: AppKioskRouteChildren = {
  AppKioskProjectIdRoute: AppKioskProjectIdRoute,
  AppKioskIndexRoute: AppKioskIndexRoute,
}

const AppKioskRouteWithChildren = AppKioskRoute._addFileChildren(
  AppKioskRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiCreditsRoute: typeof AppAiCreditsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCashierRoute: typeof AppCashierRoute
  AppContractsRoute: typeof AppContractsRoute
  AppCrmFunnelRoute: typeof AppCrmFunnelRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppDirectorsRoute: typeof AppDirectorsRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppGanttRoute: typeof AppGanttRoute
  AppKioskRoute: typeof AppKioskRouteWithChildren
  AppMyEarningsRoute: typeof AppMyEarningsRoute
  AppMySharesRoute: typeof AppMySharesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayablesRoute: typeof AppPayablesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPermitsRoute: typeof AppPermitsRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScanCreditsRoute: typeof AppScanCreditsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSubcontractorsRoute: typeof AppSubcontractorsRoute
  AppSupplyRoute: typeof AppSupplyRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTabelKioskRoute: typeof AppTabelKioskRoute
  AppTaxReportsRoute: typeof AppTaxReportsRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiCreditsRoute: AppAiCreditsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBillingRoute: AppBillingRoute,
  AppCashierRoute: AppCashierRoute,
  AppContractsRoute: AppContractsRoute,
  AppCrmFunnelRoute: AppCrmFunnelRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppDirectorsRoute: AppDirectorsRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppGanttRoute: AppGanttRoute,
  AppKioskRoute: AppKioskRouteWithChildren,
  AppMyEarningsRoute: AppMyEarningsRoute,
  AppMySharesRoute: AppMySharesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayablesRoute: AppPayablesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPermitsRoute: AppPermitsRoute,
  AppQualityRoute: AppQualityRoute,
  AppReportsRoute: AppReportsRoute,
  AppScanCreditsRoute: AppScanCreditsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppSubcontractorsRoute: AppSubcontractorsRoute,
  AppSupplyRoute: AppSupplyRoute,
  AppSupportRoute: AppSupportRoute,
  AppTabelKioskRoute: AppTabelKioskRoute,
  AppTaxReportsRoute: AppTaxReportsRoute,
  AppWarehouseRoute: AppWarehouseRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PassportOcrRoute: PassportOcrRoute,
  PassportPreviewRoute: PassportPreviewRoute,
  PassportReviewRoute: PassportReviewRoute,
  PassportScanRoute: PassportScanRoute,
  PassportScannerRoute: PassportScannerRoute,
  PendingRoute: PendingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  BlogAccountingGuideRoute: BlogAccountingGuideRoute,
  KioskScreenTokenRoute: KioskScreenTokenRoute,
  PIdRoute: PIdRoute,
  TabelScreenTokenRoute: TabelScreenTokenRoute,
  ApiPublicExportDatabaseRoute: ApiPublicExportDatabaseRoute,
  ApiPublicExportStorageRoute: ApiPublicExportStorageRoute,
  ApiPublicHooksApartmentSyncRoute: ApiPublicHooksApartmentSyncRoute,
  ApiPublicHooksFunnelInboundRoute: ApiPublicHooksFunnelInboundRoute,
  ApiPublicHooksPartnerSyncRoute: ApiPublicHooksPartnerSyncRoute,
  ApiPublicHooksSmsRemindersRoute: ApiPublicHooksSmsRemindersRoute,
  ApiPublicHooksWhatsappLeadsRoute: ApiPublicHooksWhatsappLeadsRoute,
  ApiPublicWaVoiceFileRoute: ApiPublicWaVoiceFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
